### ISSUE TITLE
astral sorcery doesnt recognise panzer glass as a glass block

### ISSUE THREAD

**Issue by majijn** [stfwi/engineers-decor#10]
love the new glass! its even better than my extra colours for insulating glass, 

however for some reason theyre not letting starlight beams through, while insulating glass and vanilla glasses do.

**Comment by stfwi** [comment]
That is because of the unique material composition, which unfortunately filters out a lot of wave lengths, including ultra-violett, infrared, and starlight-white ... I have no idea ;-). Maybe I have to derive from vanilla glass, which would be bad. Let's take a look if AS is open source and if so, what the detection condition is.

**Comment by stfwi** [comment]
Check  `engineersdecor-1.12.2-1.0.2-b3.jar`, I made some changes in the material properties of the glass, maybe brings AS to recognize the block as glass. Gimme feedback if this works, so we can tick this issue ;)

**Comment by majijn** [comment]
unfortunately it doesnt seem to work, neither do the windows.
edit: the windows are SO lovely, theyre mechanically exactly what i wanted when i asked for leadlights, just different texture!

**Comment by stfwi** [comment]
Oh, that's a bummer. I don't know what make AS recognizing the block, I'll send a request to them and see what they say, maybe it's an easy aspect - at least I hope so ;)

**Comment by stfwi** [comment]
OK I quickly double checked. AS appears to have a `RaytraceAssist` for that, where vanilla glass variants are noted (GLASS, GLASS_PANE, STAINED_GLASS, STAINED_GLASS_PANE). The IE insulating glass is a `StoneDecoration` block. I connot find any explict API connection in IE for AS, neither in AS for IE.

Are you absolutely sure that starlight can pass through insulating glass? (without any compat mods etc?).

**Comment by majijn** [comment]
i do recall it going through insulated glass, but now i cant get it to work for some reason :/ my bad

**Comment by stfwi** [comment]
Ok, so let's close this then. I doubt that we can do anything about it in this mod.
