### ISSUE TITLE
[1.15.2] Incompatibility with ClickMachine

### ISSUE THREAD

**Issue by ocram9** [stfwi/engineers-decor#100]
#### Description:
When I try to load my server it crashes while starting. From the crash report I thought ClickMachine was causing it, but it was working fine before and hasn't been updated in a while. After removing engineers decor the server worked again. 

The weird thing is is that adding older versions of this mod also crashed the game even though they used to be working fine together. I thought it might be related to Forge in some way but I'm not sure.

#### Logs:
- Crashlog: https://gist.github.com/ocram9/c59cec4aad1eb68690b2d8bc111fe438

#### Versions:
- Minecraft 1.15.2
- Forge 31.2.19
- engineers-decor 1.1.0-b2
- ClickMachine 3.0.2

**Comment by stfwi** [comment]
Hi, I'll need to dive deeper into that at the weekend. There was an update of the Forge mappings, which I applied. It is possible that I did not take something that changed into account, bear with me.

**Comment by ocram9** [comment]
So uh, forge 31.2.20 just released and even though I can't see anything in the changelog that would hint at fixing this issue it seems to have fixed this issue.. The server starts fine with both mods installed so it seems to have been a forge issue.

**Comment by stfwi** [comment]
[crashlog.zip](https://github.com/stfwi/engineers-decor/files/4782185/crashlog.zip)

**Comment by stfwi** [comment]
Ok, so I was also trying to quick check on that just now. I also cannot reproduce that. The code check also points to a location where no relevant call is done at all. Let's assume for now it was a single/uniquely appeared problem and close. I have it on screen now, so when something similar drops in I'm gonna dive into reproducing and fixing.
