### ISSUE TITLE
Crash pushing small tree cutter (requires Quark)

### ISSUE THREAD

**Issue by D0CTOR-ZED** [stfwi/engineers-decor#101]
I'm experiencing a repeatable crash when pushing a small tree cutter with a sticky piston.

https://pastebin.com/DKErj5qK

it doesn't crash every time the cutter is pushed.  When pushed by a relatively slow T flip flop, it eventually crashes.  The location it is being pushed into is adjacent to an Immersive Engineering capacitor set to output to the cutter and a jungle tree.  I can't say if either of these is required for the crash.  Basically, I'm trying to automate a large jungle tree farm and leaving it in place prevents the tree from growing.  This crash was done using a small jungle tree in a creative test world.

I'll post this under Quark as well as both mods are required to achieve this crash.  I feel that Quark is ubiquitous enough that this would be worth fixing.

Edit: After posting this, I reviewed Quark's issues prior to posting there and have come to the conclusion that the solution involves either preventing it from pushing the TE in the config or for the issue to be fixed on this end.  I ended up not posing this issue under Quark.

Also, I think this log should have been submitted as well: https://pastebin.com/cX3Qr9t0

Thanks for an awesome mod.  Very well done.

**Comment by stfwi** [comment]
Hi, ty for the hint. The exception is coming from my mod - for some reason the tile entity is updated when the block is not there anymore (moved away). This is probably a sync issue, and the Tree Cutter code should check for that race condition.
Fortunately I have scheduled a beta for today anyway and quickly implemented that check. Unfortunately I could not explicitly check the exact case of your setup. 
So let's keep the issue open in case the problem still persists on your machine. 
Could you double check with the new version (`engineersdecor-1.12.2-1.1.0-b2`) and close the issue if it's working now? Cheers -

**Comment by D0CTOR-ZED** [comment]
That does seem to have fixed it.  Thanks for the quick response.

I also realized that, when testing the latest version for this bug, I tested the most recent R release and not the most recent A/B/R, which was a beta.  So I can confirm that the issue was still present in that beta, but no longer appears to be present in 1.12.2-1.1.0-b2.

**Comment by stfwi** [comment]
Alright, ty for double checking with the different versions. Cheers -
