### ISSUE TITLE
[1.15.2] BUG: Small tree cutter gets destroyed/replaced by vines when tree grows (jungle tree)

### ISSUE THREAD

**Issue by winnetrie83** [stfwi/engineers-decor#105]
engineersdecor-1.15.2-1.1.0.jar
forge-31.2.30
mc 1.15.2

Whenever a tree grows (jungle tree) with vines on it , the small tree cutter gets destroyed/replaced by the vines.
 It's not something that's with only your blocks. The same happens with endrods, torches and rails and prob more.
I think it has something to do with the blocks material....
Eiher way i suggest looking into it, as it does not happen with solid blocks like stone and logs. Slabs don't break either.

**Comment by stfwi** [comment]
Hi, ty for the hint. IIRC there is a can-replace method for blocks that may help out here. It may take a bit until I can tackle that, but let's schedule already that for the next beta.

**Comment by stfwi** [comment]
Quick update, the defined material is "iron", but it is possible that a "not solid" property of the block has an effect here.
How did you produce the problem? Normally a large jungle tree does not grow around blocking ... blocks ... or so.

**Comment by winnetrie83** [comment]
What do you mean with "Normally a large jungle tree does not grow around blocking ... blocks ... or so" ?
I already told you i had the treecutter near it. So i basically made an automatic treefarm with your mod.
A blockplacer places a sapling and on the other side of that sapling is a treecutter that is cutting the tree once it has grown.
This works perfectly with most trees, but the jungle trees come with vines on the tree bark when they grow and in most cases the vines go al the way to the bottem of the tree, where the treecutter is. The vines then break the treecutter.

**Comment by stfwi** [comment]
Ok gotcha, bark vines of the single sapling jungle tree, not hanging vines of the big quad-sapling trees.

**Comment by stfwi** [comment]
Can you provide a mod list in your setup? Would be cool.
Whenever I test that, the trees either do not grow (because at least the vanilla code checks if there is space for growing), or the cutter does not get replaced with vines. So there must be something else having an effect here. I tested with Forge 31, but the only change there - according to the log - was about bucket fluid sounds.

**Comment by winnetrie83** [comment]
Here is a list of mods used at the bottem of the page(It's a modpack i made btw): https://www.curseforge.com/minecraft/modpacks/terran-civilization/files/3000634
Here is a video link where you can see what happens: https://youtu.be/JFFXn6PEsSk

**Comment by stfwi** [comment]
Ok ty, gonna take a look at this.

**Comment by stfwi** [comment]
Ok winne, it looks as something forcefully/destructively grows the tree. Must be another mod, I checked double checked the vanilla code and my code. In your video you can also see that some vines or whatever plant was on the ground there was also broken instantly when the tree grows. 
I think there's this time nothing I can do in my mod code. Update the mods in your pack for now and check if someone else has fixed a bug maybe. ( :-/ )
