### ISSUE TITLE
1.12.2 Hostile Mobs Never/Rarely Spawn

### ISSUE THREAD

**Issue by StormbringerGTX** [stfwi/engineers-decor#106]
So weirdly enough when I have the new version of Engineer's Decor loaded (I was having that crash previously and reported on that) Hostile mob spawns are almost non existent. As in I can go an entire night roaming around and not see one. Also in caves they rarely happen, and when they do it will be a small cluster of them about 3 or 4.

Some notes:
Mobs Spawners still spit out hostile mobs.
Game is not not peaceful
Game is on hard
Checked via commands that hostile mobs can indeed spawn

I have a fairly large modpack and this was a pain to figure out what was causing it, as I never would have guessed otherwise. I removed all mods I thought would be cause this and still had this issue.

It is only when I started the long journey of starting fresh and adding mods one by one did the issue happen when I got to Engineer's Decor.

Help me Obi Wan Kenobi!

**Comment by stfwi** [comment]
Hi Yoda, care taking you must ;-). The mod does not have hooks for spawning, structs or, oregen. Only the spawn-callbacks for the mod blocks (preventing that an entity can spawn in the blocks, or on them, e.g. for slabs, stairs, glass, devices). So the mods should technically not be able to have an effect on global spawning.

**Comment by stfwi** [comment]
Just double checked the vanilla spawning conditions, the mod code can't have an effect on spawning in or on other blocks.

**Comment by StormbringerGTX** [comment]
I have no clue what is happening at all. Without the mod, hostile mobs are spawning. With the mod installed they are not. Let me do some testing and see if another mod isn't playing nice with this? I dunno, but I needs me some Engineers Decor!!!

**Comment by stfwi** [comment]
Double check on several packs and on my dev server. I got normal spawning everywhere. So gonna mark this for now as not reproducible. Could you keep me in the loop if you find out something in your setup? Cheers, -

**Comment by StormbringerGTX** [comment]
I think it is safe to close and I'll open it if I come across something else but hours of testing show that my results are not conclusive! Thanks for the help!
