### ISSUE TITLE
1.12.2 Snow covers steel mesh fences

### ISSUE THREAD

**Issue by TheTinyPebble** [stfwi/engineers-decor#107]
Game version: 1.12.2
Mod version: engineersdecor-1.12.2-1.1.0

Hi,

During snowfall steel mesh fences (and presumably gates) gets covered by snow, which is unlike vanilla behaviour for snow (where snow only covers full blocks). 

See attached image for visual example.

![2020-07-08_21 11 51](https://user-images.githubusercontent.com/25732713/86965568-ad31d700-c15f-11ea-8f4a-6cb684b685aa.png)

**Comment by stfwi** [comment]
Hi, gonna take a look at the weekend. Probably missed setting “solid top side” to no.

**Comment by stfwi** [comment]
Alright, snow checks the block-face-shape, fixed that for next version v1.1.1-b2. Thanks for the hint man!

**Comment by stfwi** [comment]
Should be fixed in v1.1.1, which is no on Curse. Could you double check and close the issue if the problem is resolved on your machine? Cheers, -

**Comment by TheTinyPebble** [comment]
Issue fixed, no snow on fences after 1 Minecraft day with snowfall.
