### ISSUE TITLE
Black/Pink Missing Texture Box on Windows when combined with BetterFoliage

### ISSUE THREAD

**Issue by BlueVal** [stfwi/engineers-decor#108]
Hiya, 

Not sure if this is a BetterFoliage issue or an Engineers Decor issue.

Been playing a newly made pack for me and my partner and a few friends lately.
My partner tried to use the Windows from the Engineers Decor mod and had no issues with rendering, however on my side it shows the following.

I got a friend of mine to check it as well and he has the same bug as i do.

![2020-07-24_22 11 48](https://user-images.githubusercontent.com/36119033/88436027-554fcd00-cdfb-11ea-8f58-7c20efef5614.png)

Made an empty test instance with engineers decor, JEI and BetterFoliage as it appears in https://github.com/stfwi/engineers-decor/issues/19

Tested this on a empty flat world with only these mods loaded

Versions:
forge-14.23.5.2854
engineersdecor-1.12.2-1.1.1.jar
BetterFoliage-MC1.12-2.3.1.jar

Which produces the following result:
![2020-07-24_22 30 00](https://user-images.githubusercontent.com/36119033/88436925-41a56600-cdfd-11ea-80d7-d43c6d57047b.png)

Removing BetterFoliage fixes the issue, however i would prefer not too if possible!

The only difference in this would be our system specifications pretty much!
Looked at what differences there may be and only found the following:
Both me and my friend are on the RTX series of Nvidia with a 2080 and a 2070.
My partner is on the GTX series, with a 1060

Kind regards,
BlueVal

**Comment by stfwi** [comment]
Hi, there is a side effect with better foliage and the combined glass/wood model of ED. We could up to now not track down where that exactly comes from, but it should be gone if you enable at least mip-mapping level 1 in your video settings.

**Comment by BlueVal** [comment]
Ah i see, yeah it seems enabling this bypasses that, its quite strange as i know that my partner has not got mipmaps enabled either with BetterFoliage

I'll close this issue for now, just thought that the details may help perhaps :)
