### ISSUE TITLE
[1.15.2] Texture bug on straight steel pole head/foot

### ISSUE THREAD

**Issue by Alsett** [stfwi/engineers-decor#109]
For both the thick and thin version of the straight steel pole w/ head/foot, the texture of the foot part turns transparent if a block is placed on top of the pole. See screenshot:
https://imgur.com/a/o3tviuU

**Comment by stfwi** [comment]
Hmm, looks almost like culling. Gonna risk a glimpse at the weekend.

**Comment by stfwi** [comment]
Ya, was culling the model. Fixed, scheduled for the next beta at the weekend.

**Comment by stfwi** [comment]
Dang it, forgot to release merge that in 1.15. Now it's fixed in 1.16 already, but for 1.15 it will be then in v1.1.2-b1.

**Comment by stfwi** [comment]
Closing this one directly, I don't expect inconsistencies here, as only model files are affected (it's gonna work ;)).
