### ISSUE TITLE
[1.16.1] Client crash looking in block placer's gui

### ISSUE THREAD

**Issue by Lassendc** [stfwi/engineers-decor#112]
Forge Version is 32.0.88
Mod version 1.1.1-b4
[crash-2020-07-30_01.07.06-client.txt](https://github.com/stfwi/engineers-decor/files/4997943/crash-2020-07-30_01.07.06-client.txt)

**Comment by stfwi** [comment]
Hi, there was a change in the mappings. Please update forge and the mod. It should be compatible then. Cheers, -

**Comment by stfwi** [comment]
Did the update fix your issue?
