### ISSUE TITLE
Texture bug on iron hatch

### ISSUE THREAD

**Issue by KrAzYGEEK32** [stfwi/engineers-decor#113]
Iron hatch texture seems to render in only one direction, although place in a different angles

Minecraft: 1.16.1 
Mod:1.1.1 - b4

**Comment by stfwi** [comment]
Hi, ok ty for the hint. Let me look this weekend.

**Comment by stfwi** [comment]
Ok, that was actually only a missing blockstate property entry. Fixed ;-)

**Comment by KrAzYGEEK32** [comment]
thanks :) love your mod alot btw keep up the good work! im closing the issue
