### ISSUE TITLE
Suggestion: Some type of door and trapdoor made of steel and/or treated wood

### ISSUE THREAD

**Issue by SubjectHawk66** [stfwi/engineers-decor#115]
I was just looking for a cool industrial style door and trapdoor. Didn't really find any good ones that would fit the immersive engineering style. Also combining the trapdoor with the properties of a ladder would be useful.

**Comment by stfwi** [comment]
Hey ho. Nilhres will update the Engineer’s Doors mod. So normal doors and trapdoors will be covered by that. I have a feature request for a sliding steel door for so for a while. I can double check to do that one. Cheers, -

**Comment by SubjectHawk66** [comment]
God there should be a big list of these types of mods.

**Comment by stfwi** [comment]
Aye, a recommendation if not aware yet: "Immersive Posts" (TwistedGate), also a thingy I like using in the retro-industrial IE context ;-).

**Comment by SubjectHawk66** [comment]
I have that one, it's just the door one I haven't heard of.
