### ISSUE TITLE
Inset Light Recipe 

### ISSUE THREAD

**Issue by Kon-XIII** [stfwi/engineers-decor#118]
<img width="1911" alt="Untitled" src="https://user-images.githubusercontent.com/69606516/90073184-ac590b80-dcf0-11ea-896b-a3b9b8e7d2a8.png">

Minecraft 1.16.1
engineersdecor-1.16.1-1.1.1-b6.jar

 
The recipe currently requires you to have one inset light to begin with, can't make one from scratch.

**Comment by stfwi** [comment]
Hi, Thanks for the hint, I have fixed the conditional recipe already ;), there was also another block affected IIRC. Fix is scheduled for the weekend. Cheers, -

**Comment by stfwi** [comment]
Oky doke, engineersdecor-1.16.1-1.1.1-b7 is up on Curse. Could you double check and close the issue if the recipe's working on your pack now?
