### ISSUE TITLE
gui crash

### ISSUE THREAD

**Issue by Warbringer12** [stfwi/engineers-decor#119]
[crash-2020-08-21_21.11.05-client.txt](https://github.com/stfwi/engineers-decor/files/5111903/crash-2020-08-21_21.11.05-client.txt)
version 1.16.2-1.1.2-b2
forge version 1.16.2 33.0.20

**Comment by stfwi** [comment]
Hi, aye, it's already fixed. There was a cleanup in forge 33.0.20 that had to be adapted to. Unfortunately I just pushed the b2 to Curse before I saw the new Forge version ;/. Cheers, -

**Comment by stfwi** [comment]
engineersdecor-1.16.2-1.1.2-b3 is pushed on Curse, as the problem was reproducible and known across mods I'll close this issue directly. Thanks again for filing it! Cheers, -
