### ISSUE TITLE
[suggestion] small block breaker to store the block it breaks (have a little internal storage)

### ISSUE THREAD

**Issue by winsrp** [stfwi/engineers-decor#121]
so when breaking some blocks I normally put factory hopper to pick up stuff but some blocks fall on places the hopper can't pick them up (yes with max range), they sometimes fall on a hole on the ground or something, and it seems the hopper only picks up stuff over his level, expected but unfortunate, and then items on a lover level start to stack and get lost, this could all be avoided if the breaker had least a 1 stack of storage space to pick the block it breaks... would be a great addition.

Thanks for an excellent mod!

**Comment by stfwi** [comment]
Hi, let me think about this. I changed the drop trajectory of the breaker already that dropped items fall down (not entirely straight, but quite). The basic idea is that a contraption for placing, breaking, and collecting has to be constructed. 
Checkout the Factory Hopper upward-placing feature and tell me what you think (it should collect 2.5 blocks below it then and insert in an inventory above it).

**Comment by winsrp** [comment]
well it works with the hopper upside down but it feels so odd ... its like a sucker instead of a hopper XD, but thanks for the idea... would have never though of a hopper being placed upside down =D

**Comment by winsrp** [comment]
I would like to say that even if this works, it would be better to have some storage on the breaker.... even if it is just a single slot... XD

**Comment by stfwi** [comment]
Okay, point taken ;-). I'll put a note in my todo list to check how this can be addressed in an optional or balanced way.

**Comment by stfwi** [comment]
In v1.1.3-b1 I implemented that the Breaker directly inserts broken blocks into Vanilla Hoppers or Factory Hoppers underneath it. Should be okay for the use case and not too "spoily" according to manufacturing with contraptions. Scheduled for the next 1.16.3 mod version ;)

**Comment by stfwi** [comment]
File for 1.16.3 is up on Curse now (v1.1.3-b1).
