### ISSUE TITLE
Manual - 'Class Loading' Errors with Patchouli

### ISSUE THREAD

**Issue by COLDW0LF** [stfwi/engineers-decor#122]
Hello, and thanks so much for yet another must-have set of mods.
I can't imagine playing with IE and not having Engineers Decor, you're a godsend!

I'm getting 'class loading' errors with both of the manuals for Decor and Tools.
I've added a .txt file with the relevant part of the log, unfortunately Pastebin is completely failing to work for me at the moment.
Please feel free to let me know if the rest of the log will be of any use to you and I'll gladly upload it, or if you need any other info.

[LOG.txt](https://github.com/stfwi/engineers-decor/files/5125912/LOG.txt)

**Comment by stfwi** [comment]
Hey, thanks man. Gonna check what’s going on there at the weekend. Cheers, -

**Comment by stfwi** [comment]
Oky doke, had a quick check, was just a refactoring mess-up for 1.16.2 glitched into 1.16.1. I have pushed a maintenance release on Curse with the correction.
In 1.16.2 there are some book model issues, I may have inform vazkii/willie for that.
