### ISSUE TITLE
Steel mesh fences disappeared when the map was moved from 1.15.2 to 1.16.1

### ISSUE THREAD

**Issue by gekkone** [stfwi/engineers-decor#123]
Fences are not displayed, it is impossible to put a block in the place where they stand. But in this place you can pass. As soon as you update the block next to the fence, it immediately appears

![2020-09-02_01 08 20](https://user-images.githubusercontent.com/13663086/91911319-7d173800-ecb9-11ea-8cd9-ae16b3ca3d29.png)
![2020-09-02_01 08 22](https://user-images.githubusercontent.com/13663086/91911331-830d1900-ecb9-11ea-9cf6-afbde41d11af.png)

Minecraft: 1.16.1
Forge: 32.0.108
IngineersDecor: 1.1.3

**Comment by stfwi** [comment]
Oh man that's a long (and cool looking) corridor. I did not figure out yet how the mappings for automatic data-fixing is done in 1.16, and Mojang changed the way walls are represented - that unfortunately changes my fence, too. But the Mojang data-fixer does not apply to my fence. I will have to defer that for a while ;/.

**Comment by gekkone** [comment]
This is a super-fast subway: boats on ice))
I noticed this warning in the server logs, maybe this can help

`[31Aug2020 03:00:32.198] [Server thread/WARN] [net.minecraft.nbt.NBTUtil/]: Unable to read property: east with value: false for blockstate: {Properties:{east:"false",waterlogged:"false",south:"true",north:"true",west:"false",up:"false"},Name:"engineersdecor:steel_mesh_fence"}
[31Aug2020 03:00:32.198] [Server thread/WARN] [net.minecraft.nbt.NBTUtil/]: Unable to read property: south with value: true for blockstate: {Properties:{east:"false",waterlogged:"false",south:"true",north:"true",west:"false",up:"false"},Name:"engineersdecor:steel_mesh_fence"}
[31Aug2020 03:00:32.199] [Server thread/WARN] [net.minecraft.nbt.NBTUtil/]: Unable to read property: north with value: true for blockstate: {Properties:{east:"false",waterlogged:"false",south:"true",north:"true",west:"false",up:"false"},Name:"engineersdecor:steel_mesh_fence"}
[31Aug2020 03:00:32.199] [Server thread/WARN] [net.minecraft.nbt.NBTUtil/]: Unable to read property: west with value: false for blockstate: {Properties:{east:"false",waterlogged:"false",south:"true",north:"true",west:"false",up:"false"},Name:"engineersdecor:steel_mesh_fence"}
`

**Comment by gekkone** [comment]
Hi, this is one of the problems that does not allow me to update my small cozy server. I'm a programmer myself, although I haven't worked with Minecraft, if I showed you which way to dig, I could help you solve the problem. I understand the problem: the fence data format has changed, but the objects on the old map contain the old data format, which is no longer readable. There are suggestions as to how the CTO can be corrected. I apologize for my English

**Comment by stfwi** [comment]
Hi, I may get a some hours tomorrow to check how one can hook into `DataFixer`s, currently I have no clue yet ;)

**Comment by stfwi** [comment]
Ok, checked up on that, it seems that currently datafixing in mods is not a thing :/. I did not even find a point where I could hook into that system e.g. using a Forge event. Also in the Forge Discord there are currently no API solutions for that mentioned. It seems this will not be available too soon.

Can you try e.g. using a world editing tool to convert the state data? (I have to admit I have no clue how these tools actually work, but hear here and there that they're used to port game saves to newer MC versions with modded features)

**Comment by gekkone** [comment]
Oh, that was to be expected) Yes, I also heard about the editing tools in the world and even about the automatic utility to repair the worlds of love. Thank you, I will try to use them, if I achieve the result, I will write here, maybe it will be useful to someone else

**Comment by stfwi** [comment]
Ya, DataFixers are still not accessible for mods it seems. Let me migrate the issue to a monitoring note for upcoming versions, maybe it's re-introduced one time. I'll close this one for now. Cheers,-

**Comment by gekkone** [comment]
Oh, I forgot about that... By the way, I managed to fix the problem. However, fixers of the world do not solve it, because they do not work with mods and cannot understand that nbt data is incorrect. I wrote my own script that walked through each region and corrected incorrect data. The script was written in the evening "on the knee" so I'm ashamed to publish it here. However, if someone who is faced with this problem really needs a solution-please contact me and I will share it

**Comment by stfwi** [comment]
That's kind, ty. I'll keep it in mind if someone has similar porting issues. Cheers,-
