### ISSUE TITLE
[1.14, 1.15, 1.16] Dense Grit Dirt has no Loot Table entry.

### ISSUE THREAD

**Issue by Vaelzan** [stfwi/engineers-decor#124]
Title says it all. :)

**Comment by stfwi** [comment]
Hey man, ty telling, fixed for 1.16.2, 1.16.1, 1.15 (1.14 does not have the block yet), scheduled for the next releases. Cheers!

**Comment by stfwi** [comment]
Ok, all fixes are now up on Curse, if you could update the pack, would be perfect. Cheers, -

**Comment by Vaelzan** [comment]
Thanks for the quick fix. I actually added a loot table to the pack anyway (since we have a data pack that gets auto-loaded) but I can safely remove that for the next release. :)
