### ISSUE TITLE
should the factory hopper work with minecarts?

### ISSUE THREAD

**Issue by boneskull** [stfwi/engineers-decor#125]
I have a Minecart w/ Chest, and am attempting to use the Factory Hopper to insert into it, but it refuses to insert anything; I have tried from the top, bottom, and sides.  MC v1.15.2, ED v1.1.3

Here's a screenshot of my hopper config, just in case I messed it up

![engineers-decor](https://user-images.githubusercontent.com/924465/92774788-a8052a00-f352-11ea-8a1f-eca1b40d49e0.png)

**Comment by stfwi** [comment]
Hi man, I did not explicitly intend that, but I can check if there is a functionality in the Forge that allows to insert items into an entity (like the chest-minecart, or other modded carts with item containers). Cheers, -

**Comment by stfwi** [comment]
Aye, just double checked, should not be hard to do, at least in 1.16.3. I'll make a beta implementation for the next version.

**Comment by stfwi** [comment]
Oky, pushed the mod version on Curse, have tested this with vanilla inventory-minecarts. Could you double-check/review on your machine and close the issue if it's working? Cheers, -

**Comment by boneskull** [comment]
hey thanks, just saw this. I'll give it a try
