### ISSUE TITLE
Labelled Crates not keeping names

### ISSUE THREAD

**Issue by Inqie** [stfwi/engineers-decor#127]
Hi

So, I guess this is not a bug, but possibly an unfortunate oversight. Both Shulker Boxes and IE Crates save their names to the NBT, so when you place them down they keep their names. You can therefore tell what they are in your inventory after picking them up. Labelled Crates don't follow this trend (atleast in 1.12.2). 

I know they hold twice the inventory space, but if you have to memorize which box is which it can get confusing - and if stored in an inventory, defeats the purpose of labels. I believe it would be an improvement if either they were able to keep their name, or if they had the label display as part of the inventory icon. 

I understand if this issue is an intended feature though. But this is just my 2c.

**Comment by stfwi** [comment]
Hey ho, aye you're absolutely right there. Fixed it now in 1.16.3, not sure if/when I'll do pack-porting/old version fixes. The pace of new Minecraft and Forge versions is just so quick at the moment that it's really hard to keep up with the present issues.
