### ISSUE TITLE
lil typo

### ISSUE THREAD

**Issue by Smollet777** [stfwi/engineers-decor#129]
Don't guard from show pls. Show must go on!
https://github.com/stfwi/engineers-decor/blob/f60f35bf3f07f552ed0d39c3add189b4c5d1a9ae/src/main/resources/assets/engineersdecor/lang/en_us.json#L74

**Comment by stfwi** [comment]
"Oh deer" ;-). I can read stuff 50 times and still don't see them.

**Comment by stfwi** [comment]
Oky, quickly fixed that while I'm on it ;)
