### ISSUE TITLE
Texture Bleeding

### ISSUE THREAD

**Issue by Inonedn** [stfwi/engineers-decor#13]
I've noticing that some textures have leaks in them, causing them to look ugly, especially poles

**Comment by stfwi** [comment]
Hi, thanks for the hint, can you send a screenshot (because I don't see leaks on my machine)?
Version is engineersdecor-1.12.2-1.0.3-b2?

**Comment by stfwi** [comment]
Double checked, I don't see bleeding, but I guess what it could be (probably at the edges?), so I changed the pole model slightly. Will be in engineersdecor-1.12.2-1.0.3-b3. 

-> Please reopen the issue if you still see bleeding on the pole in the next version.

**Comment by Inonedn** [comment]
<img width="1280" alt="Screen Shot 2019-03-30 at 11 50 45 AM" src="https://user-images.githubusercontent.com/36087299/55278393-1fbbd200-52e2-11e9-859f-4c47c808cf78.png">
another texture bleeding issue I found
