### ISSUE TITLE
[QUESTION] What is the extra slot in a Small Electrical Furnace?

### ISSUE THREAD

**Issue by LiskoSlayer63** [stfwi/engineers-decor#130]
**I mean this slot:**
![dafuq_slot](https://user-images.githubusercontent.com/10125529/96288465-2907af00-0fec-11eb-9691-877f694324bb.png)

What is it for? What can I put into it?

**Comment by stfwi** [comment]
Hi, it's the auxiliary slot, put a Hopper or Factory Hopper in there to enable that the Furnace automatically draws items from inventories at the input side (marked blue). It's also mentioned in the manual (install Vazkii's Patchouli for that), but I sense the slot should somehow be marked with a shaded symbol for better recognition.

**Comment by LiskoSlayer63** [comment]
@stfwi Thanks for the reply! I didn't know that Patchouli is supported, it seems to be pretty rare.
