### ISSUE TITLE
[1.16.1] Small milking machine not completely working

### ISSUE THREAD

**Issue by AniMaid** [stfwi/engineers-decor#131]
Set around cows, cows will walk up and get milked, and right clicking on the machine with an empty hand will show that the machine is filling with milk. However, with milk as a fluid being registered by Industrial Forgoing, it will not output milk to a fluid barrel underneath it, nor will it take buckets out of a chest placed behind it or below it, and you can not use a bucket on the machine to retrieve a bucket of milk.

A little extra information, this problem only exists in SMP,

**Comment by stfwi** [comment]
Hi, I quickly double checked with the latest versions (mc1.16.3, forge34.1.23, IE4.0.1-121, IF3.1.1, engineersdecor1.1.3-b2). Everything's working there. 
Can you provide some logs and your versions to track that? Cheers ,-

![check-milker-ae-fluid1](https://user-images.githubusercontent.com/28822525/96361935-1f846100-112a-11eb-9f98-c6dab837377e.png)
![check-milker-ae-fluid3](https://user-images.githubusercontent.com/28822525/96361947-2f03aa00-112a-11eb-8915-cb1a7b3f6fa0.png)
![check-milker-ae-fluid2](https://user-images.githubusercontent.com/28822525/96361951-3925a880-112a-11eb-97bb-bd059d910d04.png)

**Comment by AniMaid** [comment]
Ah, it's probably because it's the latest 1.6.1 version then?

engineersdecor-1.16.1-1.1.5.jar

It works if I was to make a singleplayer world, it's just not outputting milk in any way on a server, as for logs, it's not my server, so I'll see what I can do.

**Comment by AniMaid** [comment]
I wasn't able to get logs from the server, and it's become moot as it's upgraded minecraft version.

However, here are all the relevant versions of mods
Minecraft: 1.16.1
Forge: 32.0.108
Immersive Engineering: 4.1.0-123
Engineer's Decor: 1.1.5

The problem exists only in multiplayer, starting a singleplayer world it works as expected. In multiplayer it works mostly as expected, but does not export milk as buckets or milk as a fluid with Industrial Forgoing in the pack

**Comment by stfwi** [comment]
Okay, ty for the version data, I'll check if I made an unintended fix in a later MC version or if this comes from under the hood somewhere (Forge also made some fixes, hooks, and feature updates in between, theoretically it can be also related to that).

**Comment by stfwi** [comment]
Just double checked the diffs and other deps. There was a change in the code from 1.16.1 to 1.16.3, but it should have worked also in 1.16.1, so in this case I presume that the problem comes from under the hood or an interface was not yet satisfied.
Maybe there are server data dropping in the next weeks, until then let's leave the issue open.

**Comment by stfwi** [comment]
Hi, gonna close this issue as I don't think we can get much more cross-mod data on this - it's likely that there was something under the hood causing the problem. If something pops up again I'll link to this issue. Cheers,-
