### ISSUE TITLE
Various incompatibilities with Quark item sorting.

### ISSUE THREAD

**Issue by Edulml** [stfwi/engineers-decor#134]
Metal crafting tables have the sort button right on the crafting grid and do not work at all. Labeled crates do have the sort buttons in the correct spot and they do work, but they will also move the item from the item frame slot making it unusable if one wants to automatically sort their containers. Latest version I experienced this on is Engineer's Decor 1.13-b2 Quark r2.4-272

**Comment by stfwi** [comment]
Hi, ty for the hint, I already added a workaround in ED version `v1.1.3-b3`. So now injected buttons from other mods should be inhibited. This is not exactly the fix that I liked to do, but there are more mods adding buttons at completely wrong positions in the GUI, and (other than Quark, Vazkii did take this properly into account) they do not have a possibility to prevent adding those buttons using config or API.
The basic issue is that these mods cannot know the whole details of slots in a GUI, and mostly somehow presume to deal with  chest-like containers. That does not match machines, crafting tables, etc. On the other side, I cannot take all possible mods that *modify* my GUIs into account.
I'll close the issue directly, as the mod GUI are as they should be now.
