### ISSUE TITLE
game crashes when crafting Small Water Freezer version 1.16.4-1.1.4-b1.jar

### ISSUE THREAD

**Issue by DDailyRandom** [stfwi/engineers-decor#141]
When trying to make the small water freezer the game instantly crashes. Putting the items in the crafting table is still okay. It also shows the small water freezer. But when I try to get the small water freezer in my inventory it crashes instantly. 
[crash-2020-12-04_21.28.43-client.txt](https://github.com/stfwi/engineers-decor/files/5645638/crash-2020-12-04_21.28.43-client.txt)
I have to know if Its something on my end or the servers end. I am not the server owner but I do know the server owner personally so I could talk to him of its server based.

hopefully this can be fixed soon :)

**Comment by stfwi** [comment]
Hi, ty for reaching out, check with v1.1.4-b2, there was a bug in the Fluid Barrel when crafting (see issue #136 here), this should be the bug you have here. 
Could you quickly confirm/close the issue if that was it (by the log it is, just to ensure)? Cheers,-

**Comment by DDailyRandom** [comment]
thank you yeah I think that was it. We will be updating the modpack then. Thanks for the response and have a nice day :)
