### ISSUE TITLE
Game Crashes when attempting to create the Small Melting Furnace

### ISSUE THREAD

**Issue by Ranniv-M** [stfwi/engineers-decor#142]
When you place the items for the Small Melting Furnace recipe it will show the item in the output, however when you attempt to pick it up the game will crash. 
[crash-2020-12-04_23.15.02-client.txt](https://github.com/stfwi/engineers-decor/files/5646668/crash-2020-12-04_23.15.02-client.txt)

**Comment by Ranniv-M** [comment]
Server continues to run, simply disconnects user.

**Comment by stfwi** [comment]
Hi, same here as in #141, the Barrel trying to modify an empty stack when crafting. Should be already fixed in v1.1.4-b2 (issue #136 here).

**Comment by stfwi** [comment]
Oky, was just confirmed in the other issue, it's definitely fixed, so updating should do the trick for your setup, too. Cheers, and ty for reaching out.
