### ISSUE TITLE
Small Milking Machine does not connect to IE pipe in Multiplayer

### ISSUE THREAD

**Issue by Kobayen** [stfwi/engineers-decor#144]
Small Milking Machine, IE pipes. Inspirations introduces Forgefluid milk.
In Single Player, IE pipes can be connected both to the top and the back of the Machine, perfectly able to drain any milk stored inside into IE wooden barrels.

Under Multiplayer, IE pipes refuse to connect. Barrels places underneath the machine wont drain it of its contents.

Versions:
Minecraft 1.16.4
Forge 35.1.5
IE 1.16.4-4.1.1-128
Engineer's Decor 1.1.4
Inspirations 1.2.1

**Comment by stfwi** [comment]
Hi, gonna take a look at this at the weekend, cheers!

**Comment by Scwestbrook** [comment]
For me, it's not connecting at all, am I just doing something wrong?

**Comment by stfwi** [comment]
Just took a quick peek, the "fluid handler" of the milking machine is only available when a fluid named "<somemodid>:milk" (registry name) is available. In the log file you should see "`[milk fluid available]`" if that was detected.
So, if IE pipes don't connect, this milk fluid detection must have failed somehow (first guess).

**Comment by stfwi** [comment]
Quickly checked in SP and on my local test server with the following versions:

      forge-35.1.13
      engineersdecor-1.16.4-1.1.4
      ImmersiveEngineering-1.16.4-4.1.1-128
      Inspirations-1.16.3-1.2.1.24
      Mantle-1.16.4-1.6.43

It's working fine there, I see your Forge version is smaller, mantle and inspirations not sure (1.2.1 vs 1.2.1.24). Could you update forge (and other if applicable) and double check again?

**Comment by Kobayen** [comment]
Its working after updating Forge and the rest. Maybe its some subtle thing that got fixed later. Maybe its a network thing. Go figure.

**Comment by stfwi** [comment]
Ok'y, thanks for the feedback, I'll close the issue then. Cheers!
