### ISSUE TITLE
[Question] Will this be updated to 1.16.4?

### ISSUE THREAD

**Issue by Scwestbrook** [stfwi/engineers-decor#145]
I'm using FORGE **1.16.4**, and I was wondering whether or not this will be updated to future versions, if there is a 1.16.4 version, can you show me the download? I love your creations so much, and this looked like it would go amazingly with your Gauges and Switches mod and IE

**Comment by stfwi** [comment]
Hi, it is already on 1.16.4 ;-], the current file is https://www.curseforge.com/minecraft/mc-mods/engineers-decor/files/3131303.

**Comment by stfwi** [comment]
Closing directly, I presume the link suffices, cheers, -

**Comment by Scwestbrook** [comment]
I see, the main file isn't 1.16 but It's still doable. I might hesitate because I have 26 MODS INSTALLED!!!!!

**Comment by Scwestbrook** [comment]
OK, installed it.
