### ISSUE TITLE
1.16.4 metal crafting table dupe 

### ISSUE THREAD

**Issue by umerrr** [stfwi/engineers-decor#147]
good old hopper 

https://user-images.githubusercontent.com/76566617/103100311-a5d18d80-461a-11eb-8066-55396d6c2396.mp4

(im sorry for my cum bow)

**Comment by stfwi** [comment]
"Ohw nohw", that's a bummer. I'll tackle that in the next days ("asap"). That's beyond cobble-for-days ;).

**Comment by stfwi** [comment]
Oky doke, the version is pushed on Curse ;)
