### ISSUE TITLE
Shingle Roof Chimney incorrect hit box

### ISSUE THREAD

**Issue by WenXin20** [stfwi/engineers-decor#149]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Engineer's Decor v1.1.5`

The inner and out Shingle Roof Chimney Trunk has an incorrect hitbox for the inner and outer corners.

![2020-12-23_11 15 51](https://user-images.githubusercontent.com/12000593/103108654-74ea5c00-460c-11eb-9a9f-1340b7d67c84.png)

**Comment by stfwi** [comment]
Oh, this should not be placeable as corner at all - well well ;-)
