### ISSUE TITLE
Missing Doors Tag

### ISSUE THREAD

**Issue by WenXin20** [stfwi/engineers-decor#150]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Engineer's Decor v1.1.5`

Doors could use the `minecraft:doors` and `minecraft:wooden_doors` block and item tag. The tags allow villagers to open the doors as well as be used in recipes.

**Comment by stfwi** [comment]
Hi, good point, I quickly added the tags and made some small changes that both door wings open also when villagers operate it.
