### ISSUE TITLE
[1.16.4] Rare crash on ctrl+shift

### ISSUE THREAD

**Issue by KR33PYK1NG** [stfwi/engineers-decor#151]
Sometimes if you open mod's creative tab, press ctrl+shift and hover over many items as fast as you can, the game will crash.
Crashlog: https://pastebin.com/7sEG7Uhp
I haven't found a reliable way to reproduce this, but it definitely happens in a semi-big modpack.

Forge 35.1.28
Engineer's Decor 1.1.5

**Comment by stfwi** [comment]
Hi Cr33py, ty for the CR, I have added a piece of code to circumvent the problem - it is likely related to mix-in cross compat, there are altered tooltip inputs that need to be taken into account now in my text processing. 
Now my problem is that I cannot provoke the crash on my machine (also not with Astral), would it be possible for you to check again with the attached jar if you also do not get it anymore? (Would be brilliant). It's the WIP version for the next beta.
[2021-01-01-engineersdecor-1.16.4-1.1.6-b2-issue151.zip](https://github.com/stfwi/engineers-decor/files/5759509/2021-01-01-engineersdecor-1.16.4-1.1.6-b2-issue151.zip)
Cheers!

**Comment by KR33PYK1NG** [comment]
Can confirm that the issue is gone.

**Comment by stfwi** [comment]
Oky many thanks for double checking!
