### ISSUE TITLE
[1.16.4] Crash when handling full Labeled Crates

### ISSUE THREAD

**Issue by NielsPilgaard** [stfwi/engineers-decor#157]
Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/1010

We're unsure of the exact cause, but the crash report seems to indicate an error in the code.

[Crash-report](https://pastebin.com/6ChzbLKT)

### Version
- Forge-1.16.4-35.1.37
- engineersdecor-1.16.4-1.1.6

**Comment by stfwi** [comment]
Hi NillerMed, oh my IDE auto included java.fx.Pair (not the google one) and I didn't see it ;). 
I push the fix with the mc1.16.5 update today (mod version v1.1.7). Cheers!

**Comment by stfwi** [comment]
Ok, should be fixed. I made a brief double check on my local server, but currently don't have an Enigmatica6 world there. The exception message was quite clear though what the problem was. Cheers!

**Comment by stfwi** [comment]
It's up on Curse now. Could you, when you get feedback and it's ok, close the issue? Cheers,-

**Comment by NielsPilgaard** [comment]
I trust that this does the trick, will re-open otherwise :D Thanks a lot!
