### ISSUE TITLE
Small Fluid Collection Funnel vanish waterlogged blocks

### ISSUE THREAD

**Issue by ZoMadeStuff** [stfwi/engineers-decor#158]
When the Small Fluid Collection Funnel collect water from above if the water was a waterlogged block it will vanish the block

**Comment by stfwi** [comment]
Hi, what? Why did I do all the work with the Block Breaker for if the Funnel covers that already? ;)
I presume you're on 1.16.4/1.16.5?

**Comment by ZoMadeStuff** [comment]
Yes 1.16.4

**Comment by stfwi** [comment]
Oky, unfortunately I wasn't able to dig into the matter this weekend, so a fix version will be earliest next weekend :/

**Comment by stfwi** [comment]
The fix version is on Curse now. Closing directly as I am quite sure the bug is fixed. Ty again for reaching out!
