### ISSUE TITLE
Factory Block Placer can't place blocks in CompactMachines machine

### ISSUE THREAD

**Issue by XFactHD** [stfwi/engineers-decor#160]
The Factory Block Placer is unable to place any blocks inside of a CompactMachines machine and drops them instead.
The server does not spit out any errors on the console.

This setup works perfectly fine in the overworld:
![2021-02-16_19 05 30](https://user-images.githubusercontent.com/11262040/108103674-8e4ada00-708a-11eb-98b8-7a874e24709f.png)
But it breaks in the CompactMachine dimension:
![2021-02-16_19 06 57](https://user-images.githubusercontent.com/11262040/108103682-90ad3400-708a-11eb-94b7-113d8ab99131.png)

### Versions
Forge: 1.16.5-36.0.10
Engineer's Decor: 1.16.4-1.1.7
CompactMachines: compactmachines-4.0.0-alpha.6.jar

**Comment by stfwi** [comment]
Hi, risked a quick peek today and edited a replacement-check, fix is scheduled for `v1.16.4-1.1.8-b2`. Thanks for reaching out!

![2021-02-17_21 35 22](https://user-images.githubusercontent.com/28822525/108265163-b4df4280-7168-11eb-865c-dbeeb6d44680.png)

**Comment by stfwi** [comment]
Alright, fix is uploaded (engineersdecor-1.16.4-1.1.8-b2), cheers!

**Comment by XFactHD** [comment]
Thanks for the heads-up
