### ISSUE TITLE
[1.16.5] Crash when placing Redstone Controlled Fluid Valve

### ISSUE THREAD

**Issue by maham** [stfwi/engineers-decor#161]
### Before reporting:
Couldn't find any applicable open or closed issue. Duplicating this issue on the Immersive Engineering issue page. [link](https://github.com/BluSunrize/ImmersiveEngineering/issues/4656)

### Description of the issue:
Crash to desktop when placing a Redstone Controlled Fluid Valve from Engineer's Decor between an IE Fluid Pipe and a Refinery output. After reconnecting to the server everything seems all right and the valve is still connected.

### Crashlog:
https://pastebin.com/vnsmVUHY

### Versions & Modlist
MC: 1.16.5
Forge: 36.0.13
IE: 4.2.1-131
Engineer's Decor: 1.1.7

**Comment by stfwi** [comment]
Hi, from a quick glimpse into the log I am not sure what it can be. I may have to synchronise with Blu or Malte, they may have an idea. Gonna dig deeper at the weekend, cheers, -

**Comment by stfwi** [comment]
Ok, briefly double checked - the fluid cap and handler is pretty standard and should not cause this. As malte mentioned in the corresponding IE issue thread this may be related to another problem. I leave the issue open in case something has changed under the hood and a change is needed.

**Comment by maham** [comment]
I think you can close this. Had the same crash when I placed an IE pump next to a pipe so it's not really related to Engineer's Decor.

**Comment by stfwi** [comment]
Oky, thanks for the info. Aye, the problem seems to be related to something under the hood of ED and IE. Ty again for reaching out, cheers,-
