### ISSUE TITLE
[1.16.5] items placed by Building Gadgets are placed with waterlog set to true 

### ISSUE THREAD

**Issue by b52src** [stfwi/engineers-decor#162]
items placed by Building Gadgets are placed with waterlog set to true  Items i specifically noticed ate windows, roof, all the lights and the beams as well. building Gadgets is looking at a workaround but may be due to the default state of the block placed reference this issue: Direwolf20-MC/BuildingGadgets/issues/579

so right now if i try to paste a building it is literally crying: https://i.imgur.com/C7acirl.jpg

**Comment by stfwi** [comment]
Hi, oh that looks like a lot of Sponge work ;/. Without looking at the code now - it's very likely a construction tag preventing the default state to be correct.

**Comment by stfwi** [comment]
Yepp, "copy-paste" bug in the lib, state container base state instead of `super.getDefaultState()`. Fixed and scheduled, likely pushed this weekend. Cheers!

**Comment by stfwi** [comment]
Oky the engineersdecor-1.16.4-1.1.8-b2 is up on Curse ;-) , cheers!

**Comment by b52src** [comment]
sweet thanks
