### ISSUE TITLE
[1.16.5] Crash when climbing three or more iron hatches

### ISSUE THREAD

**Issue by kappa-maintainer** [stfwi/engineers-decor#163]
Step 1:
![2021-02-18_22 56 38](https://user-images.githubusercontent.com/11038263/108442520-26ff7680-7292-11eb-90c1-1b5d06820140.png)
Step 2:
![2021-02-18_22 56 54](https://user-images.githubusercontent.com/11038263/108442575-3ed6fa80-7292-11eb-8db8-9fb3338c92b6.png)
Step 3:
Climb it and [crash](https://paste.ubuntu.com/p/WRFT2CFm8G/)

**Comment by stfwi** [comment]
Hi, it's already fixed and will be pushed with version v1.1.8-b2 this weekend. Cheers!

**Comment by stfwi** [comment]
Oky, fix version is up on Curse, closing. Ty again for reaching out!
