### ISSUE TITLE
Duplication Glitch with Metal Crafting Table 

### ISSUE THREAD

**Issue by splashnccs** [stfwi/engineers-decor#166]
So doing this requires two people, but if my friend and I are sharing the metal crafting table, we can each pull out the final item, getting two items out of the recipe. Note, we're playing on the most recent version of Brass on 1.16.5.

For example, if one person puts in 9 diamonds to make a diamond block, we're able to each pull out a diamond block. 

This only happens if one person is already working on the crafting table, and the second person is NOT looking. The person completes the recipe but doesn't pull the item out. Second person then looks at the crafting table with prepared item and then either person can pull out the completed item, and a second completed item remains. If the second person looks away _after_ the crafting process, the duplicate item disappears. 

Obviously this is an odd use case, but probably not that uncommon when people are crafting items together. We're able to consistently do it with any items that we can craft in the crafting table. If the items are stacked and player one shift-clicks all the the items out, then only one item is available to the second person.

**Comment by stfwi** [comment]
Hi splash, at the first look this looks like https://github.com/stfwi/engineers-decor/issues/138. I am not sure what the latest version of Brass is - could you double check if the mod version is up to date (the fix version is `engineersdecor-1.16.4-1.1.8`), and gimme feedback if the problem is still in this? Cheers,-

**Comment by splashnccs** [comment]
Hi, the version in the modpack that I'm using is engineersdecor-1.16.4-1.1.8-b1

**Comment by stfwi** [comment]
Hi, this one still has the bug, can you retry with the release version engineersdecor-1.16.4-1.1.8? Cheers,-
