### ISSUE TITLE
Ladders no longer climbable as of Forge 36.0.45

### ISSUE THREAD

**Issue by D0CTOR-ZED** [stfwi/engineers-decor#167]
I've tested instances for 1.16.5 with Forge versions 36.0.45 and 36.0.46 using engineersdecor-1.16.4-1.1.8.  Neither of the ladders (treated wood and metal) in engineer's decor are now climbable.

**Comment by stfwi** [comment]
Hi zed, thanks for the hint! I included the fix in the today's push (was just a minute adding a few lines of code - a feature was dropped in forge ~.45, but there is another more convenient "ladder convention" in forge that can be used instead). Gonna close directly, cheers!
