### ISSUE TITLE
[Feature Request] Fluid Incinerator

### ISSUE THREAD

**Issue by sarim** [stfwi/engineers-decor#168]
Would be great.

**Comment by stfwi** [comment]
Hi man, let me (before thinking about if and how) let met double check with BluSunrize if there are already plans for something similar like a Fluid Evaporator.  Cheers,-

**Comment by ghost** [comment]
Adding my vote to this feature request. Would love to see something like this added.

**Comment by stfwi** [comment]
Oky, I need to defer the implementation here, and transfer it into my taskbook;
