### ISSUE TITLE
[Feature Request] JEI "+" button support for Treated Wood Crafting Table

### ISSUE THREAD

**Issue by Sixdd6** [stfwi/engineers-decor#17]
In the standard minecraft crafting table (with JEI installed) there is a "+" button in JEI on each recipe which when clicked moves the items from that recipe from your inventory to the crafting grid.

I don't know whether this is a non-trivial feature request but it would be nice to have this mod compatibility.

**Comment by stfwi** [comment]
Hi, already done, including crafting assist (history re-fab) . Will be pushed with 1.4b1 ;)

**Comment by stfwi** [comment]
Hi, v1.0.4b1 is pushed, could you double check if the usability is ok for the crafting table (basically if the issue is covered well enough) ? Cheers -

**Comment by Sixdd6** [comment]
Testing now..

Working great, can consider this one closed.

**Comment by stfwi** [comment]
Wow that was fast, perfect. Thanks again for pushing ideas into the mod!
