### ISSUE TITLE
[1.16.5] Treated Wood Windows Dupe Bug

### ISSUE THREAD

**Issue by NielsPilgaard** [stfwi/engineers-decor#170]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/1793

> **Describe the bug**
> if you place a treated wood window by clicking on the window to place another one, you don't use up a window in the process. You will, however, receive one when breaking it.

### Versions
- engineersdecor-1.16.4-1.1.10
- Forge-1.16.5-36.1.0

**Comment by stfwi** [comment]
Mornin', will tackle it about on Sunday, cheers

**Comment by stfwi** [comment]
Hi, alright the fix version `engineersdecor-1.16.4-1.1.11 ` is up on Curse. Was a one-liner, so I'll close directly. Cheers!

**Comment by NielsPilgaard** [comment]
Awesome, thanks :D
