### ISSUE TITLE
Implement CraftingTweaks integration

### ISSUE THREAD

**Issue by EliantenHolder** [stfwi/engineers-decor#171]
It would be great if it was possible to use the Crafting Tweaks buttons with the Metal crafting table. Crafting Tweaks enable you to rotata, balance and/or clear the crafting grid using three buttons.

According to the CraftingTweaks readme it should be as simple as sending a IMC message to CraftingTweaks (see: https://github.com/blay09/CraftingTweaks)

**Comment by stfwi** [comment]
Hi, I was experimenting already with CT integration (quite a while ago), my problem with it is that the buttons don't fit into the GUI.
The Metal Crafting Table also comes with some own more subtle tweaks, in short:
- shift clicking stacks already moves the items balanced into the crafting grid.
- ctrl-shift clicking moves all same stacks also into the crafting grid.
- ctrl-shift clicking with an empty crafting grid moves (all same) stacks between table and player inventory.
- if there is a recipe collision, a button to cycle through appears.
- mouse-wheeling over the output slot increases/decreases the grid stack size.

So, I would like - in this case - to stick to these "internal features" rather referencing an external API for this although I am aware that CT is quite popular and well known.
Nonetheless, thx for reaching out! Cheers,-
