### ISSUE TITLE
Dark Shindle Roof Block un-chisable

### ISSUE THREAD

**Issue by Rodg88** [stfwi/engineers-decor#172]
You can't use the plain block form of the dark shingles with chisels and bits. Is it a tile entity for some reason?

**Comment by stfwi** [comment]
Hi, no there is no tile entity for that block. Could be the block model, shape, or property definitions. I remember that the roof blocks were quite hardly affected by the rendering changes in recent versions, and I experimented a lot to get it look okayish again. Gonna take a look if the full-block was altered there, too.

**Comment by stfwi** [comment]
Ok, it was merely the existence of the method for getting the block shape that inhibited chiselling, so removed that for the very basic blocks. Fix is gonna be included in the next mod release.

I've noticed one interesting thing (just aside): The C&B devs have - as a major coolness factor - added an magnifying glass for inspecting if (and also why not) a block is compatible, while holding that in your hand you get looking-at-info and item-hovering-info. Very cool:

![fix-ed-cab](https://user-images.githubusercontent.com/28822525/113610803-e6936680-964d-11eb-9eb8-8fbdd5bf27c2.png)

**Comment by stfwi** [comment]
Oky the fix is up, I'll close this then. Cheers,-
