### ISSUE TITLE
Sandstone Ornated Clinker Brick voids when broken

### ISSUE THREAD

**Issue by czbuendel** [stfwi/engineers-decor#175]
Mod Version 1.1.12
Forge Version 36.1.12
Installed on an instance with just ED and JEI.

When the Sandstone Ornated Clinker Brick is broken it simply disappears and doesn't drop. 
I'm seeing no issues in the log files.

**Comment by czbuendel** [comment]
I took a quick look through the jar and couldn't find a loot table for it which may be the issue.

**Comment by stfwi** [comment]
Hey ho , cheers for the hint - forgot the loot tagble script to run, so the LT was not there actually.
(The 1.12.2 in your description I presume was 1.16.4/5 because of the forge version data?)

**Comment by czbuendel** [comment]
Oh I was just giving the prefix after the mod version. 
Was using engineersdecor-1.16.4-1.1.12

**Comment by stfwi** [comment]
Oky, fix version `engineersdecor-1.16.4-1.1.13-b2`  is up on Curse. Just watched Valen playing EL2 while fixing - he really seems to like pointing at the bugs of that mod ;-), funny thing.

I'll close this one then, keep it up man, cheers,-
