### ISSUE TITLE
[1.16.5] Recipe for Small Mineral Smelter duplicates input Fluid Barrels

### ISSUE THREAD

**Issue by TheRealWormbo** [stfwi/engineers-decor#178]
Mods:
* Engineer's Decor: 1.1.11
* Forge: 36.1.0
* Other mods in use: (see include list for [The Phoenix's Assorted Goodies](https://www.curseforge.com/minecraft/modpacks/the-phoenixs-assorted-goodies-a-generalist/files/3273269))

Problem description:
I want to craft multiple Small Mineral Smelters, so I add the required multiples of all stackable ingredients into the crafting grid and one (non-stackable) lava bucket. When I take out the (single possible) Small Mineral Smelter, the crafting grid replaces the lava bucket with an empty bucket (which I assume is on purpose) and reduces the size of most other input item stacks item by one. However, it also increases the size of the Fluid Barrel input stack. This stack size increase can go way past the usual limit of 64 and seems to follow the formula (previous size - 1) × 2.

In the attached screenshot I set up a 64-stack of each ingredient and a lava bucket in the center, then took out the result. (You can't see my cursor, but I'm holding the Small Mineral Smelter.) After closing the crafting UI, my inventory contains a stack of 64 Fluid Barrels and another one of 62, and those are confirmed to not be ghost items.
![2021-05-08_22 27 37](https://user-images.githubusercontent.com/7620864/117553164-33ed6400-b050-11eb-92ef-9301184f7a2f.png)

**Comment by stfwi** [comment]
Hi wormbo, quickly took a look, the problem came from a definition in the Fluid Barrel. Fix is scheduled for next mod version `1.1.14-b1`. I'll write a note and close when it's up on Curse Forge. Cheers man!

**Comment by czbuendel** [comment]
Sorry linked the to the wrong issue when doing updates.
I apologize.

**Comment by stfwi** [comment]
Hi, no worries. As the fix version is out I'll close this one. Cheers!
