### ISSUE TITLE
[request] fluid pump extender(?)

### ISSUE THREAD

**Issue by majijn** [stfwi/engineers-decor#18]
seeing as how you're adding fancier things with this, may I request adding a block that lets a pump pull from the bottomface of a block?
so that I can use IE's pumps to work on the astral sorcery lightwells/chalices, which can be interacted with mechanically only on the bottom face

or something like a port extender
https://github.com/Da-Technomancer/Essentials/issues/8

**Comment by stfwi** [comment]
Hey ho, fluidics is a new field for me, but as far as I could see up to now it appears to work with the cap system like item handlers - so should be possible. Now we need to make a "spec" that is general enough for common use cases and also covers your use case. What about something like a "reverse version" of a fluid placer. So would collect a fluid in the world next to it, and store that in its 1 bucket (or two bucket) storage. A pump could retrieve the fluid from that storage. Would such a device cover your use case?

**Comment by majijn** [comment]
nope, unfortunately, lightwells are tiles , and they can omly be interacted on the bottom face with fluid hoppers and whatnot.
what im after is something that can pull fluids from a bottom face of a fluid inventory and plays nicely with fluid pumps so that i dont have to buff fluid hoppers to the point where they make ie fluid pumps useless, i wanna have to use IE , even if i have to use another mod to bridge the gap, if that makes sense

i may try to get some screenshots for you in a bit  

edit: if this is out of the scope of the mod , tho, id understand, seems like this is a bit niche of a need :(

**Comment by majijn** [comment]
while I can connect fluid funnels into a pump like this
![2019-04-20_15 30 57](https://user-images.githubusercontent.com/18368034/56458815-900ebe00-638b-11e9-9a5a-b8d396ee5220.png)
 it means I'm not extracting all the fluid from the lightwell at the pump's speed, but at the funnel's speed, if I buff the funnel in the config to where It matches the pump, i end up not needing the pump at all.

so what I would like is something like this
![2019-04-20_15 31 09](https://user-images.githubusercontent.com/18368034/56458839-cf3d0f00-638b-11e9-8158-a29e9c6f30ef.png)
![2019-04-20_15 32 27](https://user-images.githubusercontent.com/18368034/56458840-cf3d0f00-638b-11e9-8e6d-22d28d6faee7.png)
but that I can set the top face to input, and have it act as part of the pump, ideally.

**Comment by stfwi** [comment]
Ok, got it now. I'll put this on the list, so that when tackling fluidics it's considered. Not sure yet how this can be done, suppose it's similar to item storage and transfer.

**Comment by stfwi** [comment]
Ooook, I added an experimental device in beta8. It should be able to pull out fluids when a pump connected to its output port starts draining.

**Comment by majijn** [comment]
that's exactly what i wanted! however is seems to not check how much fluid there is to extract, so it just ends up acting like a creative source of fluid
![2019-05-01_05 18 15](https://user-images.githubusercontent.com/18368034/57004661-f63be200-6bd0-11e9-8c01-32927a0246c0.png)

![2019-05-01_05 28 46](https://user-images.githubusercontent.com/18368034/57004805-49fafb00-6bd2-11e9-92c2-c1548d996d47.png)
![2019-05-01_05 28 48](https://user-images.githubusercontent.com/18368034/57004806-49fafb00-6bd2-11e9-8d70-59904c37765a.png)

![2019-05-01_05 57 05](https://user-images.githubusercontent.com/18368034/57005340-a44a8a80-6bd7-11e9-8257-7a4d5cdbce47.png)
![2019-05-01_05 57 05_2](https://user-images.githubusercontent.com/18368034/57005341-a44a8a80-6bd7-11e9-9f77-1e48d9201c3f.png)

**Comment by majijn** [comment]
i somehow managed to make it get stuck with 50 mb of creosote
![2019-05-01_05 27 25](https://user-images.githubusercontent.com/18368034/57004791-289a0f00-6bd2-11e9-8233-2670c288b8c3.png)
![2019-05-01_05 27 27](https://user-images.githubusercontent.com/18368034/57004792-289a0f00-6bd2-11e9-8b35-f6343f4273e4.png)

**Comment by majijn** [comment]
![2019-05-01_06 31 29](https://user-images.githubusercontent.com/18368034/57005769-02c53800-6bdb-11e9-9d3e-d97f4f2f79e5.png)
![2019-05-01_06 31 38](https://user-images.githubusercontent.com/18368034/57005770-02c53800-6bdb-11e9-9e1c-9938fdb4481b.png)
![2019-05-01_06 33 01](https://user-images.githubusercontent.com/18368034/57005771-035dce80-6bdb-11e9-99aa-2d521e379472.png)

in this set up it voids fluid unless the metal barrel is prevented from outputting fluid into the accumulator with a redstone signal

**Comment by stfwi** [comment]
Yah I there's some "debugging" to do. I have some "basic requirements" for that thing: 
- not drain fluid when they are not requested by a pump, 
- initial vacuum suction delay,
- allow explicit filling of the internal container, 
- balanced drain if possible, with round robin random fluid init when no specific fluid is requested,
- low CPU activity when idle (not drained or by the pump requested fluid not available)
- initial "drip-in" of fluids so that pumps detect that there is fluid available and start pumping.

I need to search a mod for adding some creative fluid tanks and voids for testing that stuff ;)

**Comment by stfwi** [comment]
Testing version b9: right click on the block to see input/output/buffer tank stats. So we can check voiding and  "automagical" fluid generation. If the I/O balance is correct the accumulator should work with the adjacent blocks.

**Comment by stfwi** [comment]
If you have time, could you double check if this works correctly with your testing setup? Would be brilliant. Then the device would be non-experimental in 1.0.5-b1.

**Comment by majijn** [comment]
they're working great! tysm!

**Comment by stfwi** [comment]
Perfect, thank for double checking. So Let's put it in the next version's b1, see if there are other people have trouble with compat and then release it ;)

**Comment by stfwi** [comment]
Ok, no complains so far, and I tested a bit again. So I close this.
