### ISSUE TITLE
[Feature Request] Powdercoated Steel

### ISSUE THREAD

**Issue by breakerator** [stfwi/engineers-decor#181]
I love the look and functionality of many blocks, railings in particular, but they're all just steel colored.  How about adding a way to color them, like a powdercoating system or just a paint sprayer?

**Comment by stfwi** [comment]
Hi, thanks first of all for the input. I refrain adding it, as the whole mod design is specialized around this "steely" retro industrial factory look. It's mainly meant to be a cosmetic detailing of Immersive Engineering styled buildings and machine yards. Adding colour variants will cause an explosion of blocks (or blockstates) that I would not be able to maintain (if added to the railing it has to be added to all steel blocks for consistency). I have to admit there is only one colouring feature concerning Rebar Concrete that I am thinking of adding in the future, but this is for or area/floor markings known from factories.
Cheers man,-
