### ISSUE TITLE
Solar Panel doesn't output power directly into IE capacitor

### ISSUE THREAD

**Issue by ghost** [stfwi/engineers-decor#182]
Hello,

Placing a Solar Panel directly on top of an LV or HV capacitor does not fill the capacitor with power (as I expected it to). I double checked to make sure that the top of the capacitors was correctly set to Energy Input but still nothing. Placing an HV Connector to the bottom of the Solar Panel and running a wire to the capacitors worked correctly. It'd be really nice to be able to just drop a Solar Panel directly onto the capacitor and have it fill with power.

Minecraft 1.16.5
Forge 36.1.30
Engineer's Decor 1.1.14-b3
Immersive Engineering 5.0.0-135
(I am using additional mods as well and can provide a full list if it would be helpful).

**Comment by stfwi** [comment]
Hi, I quickly double checked with your versions, it does work in my setup (it is actually the intended standard case to have Capacitor buffers underneath the panels). 
Can you double check by right clicking the Solar Panel? It will show its internal State Of Charge (SOC in %) and feeding rate. It charges up its internal battery to 20% before feeding into the grid (This was added quite a while ago). 
As the capacitors have a quite high input current rating, the energy will be transferred quite quickly from the panel into the capacitor, and the internal panel charge-up will start again. When the capacitor is full and you have a continuously drawing consumer on its output, the panel will top-up the capacitor frequently.

Cheers man!

**Comment by ghost** [comment]
Ah, I did not realize that the Solar Panel doesn't feed into the capacitor until it reaches 20% SOC. That explains why it worked when I hooked up the cables (I just dug out under the Solar Panel to add the cables which gave it time to build up energy).

I just tried it again directly on top of a capacitor and waited for it to reach 20% SOC and confirm that it does indeed move energy to the capacitor at that point. Guess I was just being too impatient earlier.

Thanks for checking and for the information about how the Solar Panel works. Appreciate all the work you do on your mods!

**Comment by stfwi** [comment]
Hi, perfect that, glad it worked out and was not e.g. a cross compat issue or so - which would have been absolutely an option ;) Cheers,-
