### ISSUE TITLE
No running particles

### ISSUE THREAD

**Issue by LeKripiY** [stfwi/engineers-decor#185]
Hello, so i've seen that if you run on certains blocks (gas concrete for example) the running particles would be of the purple checkered missing block.
Now I don't if it's an incompatibility with optifine or dynamic surrounding but it's there.

**Comment by stfwi** [comment]
Hi, not sure, which version are you running on?

**Comment by LeKripiY** [comment]
latest one on 1.16.5 (1.1.14)

**Comment by stfwi** [comment]
Okay, I put it on the list to check, cheers,-

**Comment by stfwi** [comment]
Oky, just double checked, the particles are as normal with v1.1.18/forge 1.18.1-39.0.5. There are also no special aspects that can be modified in the mod code. Can you update and double check again? Cheers,!
