### ISSUE TITLE
Crashes on load

### ISSUE THREAD

**Issue by imagelesskink** [stfwi/engineers-decor#186]
Engineer's Decor throws an error and crashes when starting Minecraft (1.17.1, forge version 37.0.50)
[latest.log](https://github.com/stfwi/engineers-decor/files/7087917/latest.log)
[debug.log](https://github.com/stfwi/engineers-decor/files/7087918/debug.log)
[crash-2021-08-31_23.01.27-fml.txt](https://github.com/stfwi/engineers-decor/files/7087919/crash-2021-08-31_23.01.27-fml.txt)

**Comment by stfwi** [comment]
Hi, oky `ToolType` not found ... I'll take a look what this is ;-). Thanks for the logs, Cheers,-

**Comment by stfwi** [comment]
Alright, updating Forge did the trick already. Could you take a glance if the crash it's also gone on your machine and close if so? Cheers man,-

**Comment by stfwi** [comment]
Oky, it's on curse for a while, I presume the problem is fixed ;)
