### ISSUE TITLE
[Feature Request] 2 block-wide variant of the steel mesh fence gate

### ISSUE THREAD

**Issue by dan96kid** [stfwi/engineers-decor#188]
This is good for when you have a 2 block-wide path going through a steel mesh fence and want an aesthetically pleasing gate that fits in on it.

**Comment by stfwi** [comment]
Hi, ty for the hint, I'll consider it for a future version. Need to double check how the gate wings fit into the block space though. Cheers,-

**Comment by stfwi** [comment]
{preparing repository archiving}
