### ISSUE TITLE
Crate item display not working

### ISSUE THREAD

**Issue by TheRealArchie** [stfwi/engineers-decor#189]
![2021-10-13_16 41 18](https://user-images.githubusercontent.com/80304455/137156137-0fc8d3aa-d4f0-4a79-9f50-ef9e1f7d4c29.png)

Crate item display not working

Nothing was changed, it was just gone one day.

**Comment by stfwi** [comment]
Hi, can you attach a log for this? I don't know the version and also not if there was an exception in the renderer. Cheers,-

**Comment by TheRealArchie** [comment]
Which file do you need? Sorry for the wait

**Comment by stfwi** [comment]
Hi, the latest.log should do, you can zip it up and drop it into this thread if you like. Cheers,-
