### ISSUE TITLE
[Bug] Broken window texture with Better Foliage

### ISSUE THREAD

**Issue by rai-en** [stfwi/engineers-decor#19]
Both wooden and steel framed window textures break when installed alongside Better Foliage. Those are the only two affected blocks and the problem doesn't seem to be version specific. It doesn't matter if Better Foliage is enabled for it to occur, just that it's installed. Running without Optifine.
 
![2019-04-25_19 47 37](https://user-images.githubusercontent.com/50001839/56776627-1152c000-6793-11e9-94d2-89e9ed844380.png)

**Comment by stfwi** [comment]
I'll go into this this weekend. Must have something to do with multilayer rendering (only windows have that). Thanks for taking the time to analyse and going to the bottom of the issue!

**Comment by stfwi** [comment]
Aye, had to use cutout-mipped instead of cutout for multi-layer model.

**Comment by stfwi** [comment]
v1.0.4-b4 dist jar is pushed, could you double check if the issue is also gone on your machine? Cheers!

**Comment by rai-en** [comment]
Can confirm fixed on my end. Thanks! :)

![2019-04-26_12 49 13](https://user-images.githubusercontent.com/50001839/56826381-bddb8300-6821-11e9-97ee-b6924785da83.png)

**Comment by stfwi** [comment]
Perfect, thanks again for going into the matter, that saved me a lot of time! Cheers -

**Comment by Meatshackles** [comment]
Seems at some point this issue was reintroduced, i'm running engineersdecor-1.12.2-1.0.11-b2 and have this same issue with better foliage .

**Comment by stfwi** [comment]
Reopened, I'll double check.

**Comment by stfwi** [comment]
Quickly double checked with two instances and configs, I cannot reproduce the issue. Looks this will get a tricky one ;)
![2019-08-27-check-ed-betterfoliage](https://user-images.githubusercontent.com/28822525/63852698-318cc880-c999-11e9-8aaf-b2557a6c294a.png)

**Comment by stfwi** [comment]
Could you zip up the log and drop it into this thread? Maybe this may help to see where the issue comes from. thx -

**Comment by Meatshackles** [comment]
![Capture](https://user-images.githubusercontent.com/43080251/64067079-4f079f80-cbf0-11e9-9cd3-002306ad0114.PNG)
![2019-08-31_13 05 51](https://user-images.githubusercontent.com/43080251/64067080-4f079f80-cbf0-11e9-819b-114c18bb5910.png)
[latest.log](https://github.com/stfwi/engineers-decor/files/3562658/latest.log)
Hes the log file, a screenshot in game with the steel windows and the modlist im testing with

**Comment by stfwi** [comment]
Thx. Oh man, nothing to see in the log about model issues in the ED mod. For finding out what it is I have wrapped a testing jar (scheduled for v1.0.12b1), where I removed UV definitions in the glass pane submodel of the window. Maybe the renderer is sensitive to that.
[engineersdecor-1.12.2-1.0.12-b1-issue19track.zip](https://github.com/stfwi/engineers-decor/files/3562714/engineersdecor-1.12.2-1.0.12-b1-issue19track.zip). If it works with that I'll rebuild v1.0.11 release to contain the change, otherwise scheduled for the next beta.

**Comment by Meatshackles** [comment]
![2019-08-31_14 33 14](https://user-images.githubusercontent.com/43080251/64067794-503ec980-cbfc-11e9-9090-a3ddda71df15.png)
Same issue with the testing jar, it looks fine in inventory though.
The frame does look like its in there just something with the glass part I guess
![2019-08-31_14 34 18](https://user-images.githubusercontent.com/43080251/64067798-7fedd180-cbfc-11e9-9690-65dfac4a40a6.png)

**Comment by stfwi** [comment]
I don't get it ;[ . If ok with you I'll wrap up the current release and schedule this to 1.0.12 beta 1. It will involve a lot of fishing in the dark, and I don't want to mess up the release jar with quick changes.

**Comment by Meatshackles** [comment]
sounds good

**Comment by stfwi** [comment]
Ok, ambient occlusion changed for the window pane, I reverted that for v1.0.12-b1.
There is another thing that crossed my mind: As BF and also the window models use Mipped Cutout models, have you mipmap level at least 1 in your video settings, or 0?

**Comment by stfwi** [comment]
Ok, next try is pushed on curse ;)

**Comment by stfwi** [comment]
Did you have time to give it a check? Cheers -

**Comment by stfwi** [comment]
Closed due to stalling.
