### ISSUE TITLE
[1.16.5] Metal crafting table does not always show alternative recipes

### ISSUE THREAD

**Issue by ProsperCraft** [stfwi/engineers-decor#192]
engineersdecor-1.16.5-1.1.15

![unknown](https://user-images.githubusercontent.com/4427684/143069417-bb64b22c-47db-4b8b-a403-a4d040f433c6.png)
![unknown (1)](https://user-images.githubusercontent.com/4427684/143069532-077fb8b4-1bb6-4439-b3d5-276e4b1926c9.png)
![unknown (2)](https://user-images.githubusercontent.com/4427684/143069614-aa64ff23-7599-4cde-990a-3a0512ec660a.png)

**Comment by stfwi** [comment]
Hi Goshen, thanks for the hint, I'll check in the next days. Is that in the towncraft pack? Cheers!

**Comment by stfwi** [comment]
Same as in #193, `v1.1.16-b1` is with the Forge mps, so it should do again. Could you take a glimpse with the new version in your setup and close if it's ok now? Cheers man,-
