### ISSUE TITLE
[Feature request] Connection between metal sliding doors and steel msh fences

### ISSUE THREAD

**Issue by emanuele246gi** [stfwi/engineers-decor#194]
I was building an elevator using ED and Create blocks, but I noticed that these two blocks do not connect each others
Here is an image:
![2021-12-05_17 15 38](https://user-images.githubusercontent.com/61762317/144754791-972fe9fa-eb1b-4379-8928-4646410733d9.png)

**Comment by stfwi** [comment]
Salute! Aye, the fences connect to solid block sides only. You have a good point here, what may be needed here is a kind of wall-like centred panel to allow the door to slide in. 

Let me transfer this issue to note in my todo-book for this, so that it's taken into account for new features. Cheers!
