### ISSUE TITLE
[1.16.5] Cannot access Labelled Crate UI

### ISSUE THREAD

**Issue by nirakoji** [stfwi/engineers-decor#195]
Hello!

I just ran a comprehensive update for my modpack on my server, and when loading in, none of my labelled crates are offering me a GUI on right click. If I get extended info for TOP, I can see the contents still, and I can extract from them with hoppers - but I cannot personally access them.

Details:
Forge 36.2.20
Minecraft 1.16.5
Engineers Deco 1.1.15

Recently Updated mods:
---Added---
	Tool's Compliment
	Right Click, Get Crops
	Tanky
---Updated---
	Archer's Paradox
	Architectury API
	CC Tweaked
	CodeChicken Lib
	CoFH Core
	Collective
	Double Doors
	Ensorcellation
	ewewukek's Musket Mod
	Farmer's Delight
	FramedBlocks
	FTB Library
	Immersive Petroleum
	InsaneLib
	Iron Chests
	Jonn's Trophy Manager
	JER
	KJS
	KJS Thermal
	McJtyLib
	MineColonies
	MineColonies CC
	More Overlays Updated
	Nether Portal Spread
	RFTools Base, Builder, Utility, Storage
	Structurize
	Toast Control
	Thermal -- Cultivation, Expansion, Foundation, Innovation
        Xnet

**Comment by stfwi** [comment]
Hi, can you double check with mod version `v1.1.16-b1` if the problem's gone in on your machine? Cheers,-
