### ISSUE TITLE
[Suggestion] Hazard Stripes Block

### ISSUE THREAD

**Issue by belathus** [stfwi/engineers-decor#196]
This seemed to be the most appropriate mod to make this suggestion to, since it has hazard signs and the like.

I was thinking I'd like a hazard striped block. Something with a texture like this: https://www.bigdug.co.uk/images/products/medium/1594799444-83077600.jpg

**Comment by stfwi** [comment]
Hi, ED is a mod that is (as good as I can manage) style compliant to Immersive Engineering, which has a quite decent and rounded colour scheme - Let me think about if/how this can be fit in. Cheers,-

(As of writing, I think to recall to have seen such a block lately in 1.16.x, could you double check if there is currently no mod providing this already?)

**Comment by belathus** [comment]
A quick look around did remind me that this type of block was in Chisel, which hasn't been updated past 1.12 as far as I can tell.

It does look like they are working on a 1.16 port. Complete with a hazard block: https://github.com/Chisel-Team/Chisel/blob/1.16/dev/base/src/main/resources/assets/chisel/textures/block/factory/hazard.png

**Comment by stfwi** [comment]
{preparing repository archiving}
