### ISSUE TITLE
Block placer stopped placing blocks after mod update

### ISSUE THREAD

**Issue by Quinteger** [stfwi/engineers-decor#197]
Hello! I am playing a Valhelsia 3 modpack.
Recently I updated the server from version 3.4.5, which had engineersdecor-1.16.4-1.1.14.jar to version 3.4.8 with engineersdecor-1.16.5-1.1.16-b1.jar.
After updating, both existing and newly crafted block placers ceased block placing and now just throw out items instead.
I don't think there is an item drop mode for them, and the manual only mentions it as a last resort if the item cannot be placed in the world at all. However, I tested this with oak logs and cobblestone with block placer looking at air, which should be a perfectly good scenario.
The modpack devs recommended creating a bugreport here, so there I am.
Please help figure this out. Cheers and happy new year.

**Comment by stfwi** [comment]
Hey ho, happy new year, too; The problem looks like related to #193, I just uploaded `engineersdecor-1.16.5-1.1.16-b2` for fixing it to Curse. Could you double check if the fix did also resolve the problem in your setup and close? Cheers,-

**Comment by Quinteger** [comment]
Sorry for taking so long to reply, the modpack updated to 3.4.9 with `engineersdecor-1.16.5-1.1.16-b2` and it works fine again.
Thanks for the help!
