### ISSUE TITLE
[1.18.1] Small Mineral Melting Furnace works inconsistently.

### ISSUE THREAD

**Issue by ArchieBeepBoop** [stfwi/engineers-decor#198]
On 1.18.1, small mineral melting furnaces work incredibly inconsistently. Even with a proper fixed input of cobblestone through pipez pipes, pipes underneath said mineral melting furnaces and whatnot, they will often get stuck in the following state:
![image](https://user-images.githubusercontent.com/53913550/149708041-f55ca0f4-4342-434c-b949-9922c65de18a.png)

I've been using these solely to create lava and most of the time they will stop working, staying stuck in that state where they do not reset before accepting another cobblestone to melt into lava, requiring someone to add a lever to them and toggle the lever on and off before they start working again.

This sometimes does not happen if the output of lava is slow enough for whatever reason, but happens almost all the time if you use a pipe that pulls the lava from the furnaces faster. This will even happen with default IE pipes, although that scenario is rarer.

**Comment by stfwi** [comment]
Hi, ty for digging deeper into the matter. Some things are beta yet ;). I checked with a fluid barrel when porting to 1.18.1, pushing lava in these should do. You can double check if that is a workaround until I get to check what's going wrong then draining lava. Cheers ,-

**Comment by ArchieBeepBoop** [comment]
> Hi, ty for digging deeper into the matter. Some things are beta yet ;). I checked with a fluid barrel when porting to 1.18.1, pushing lava in these should do. You can double check if that is a workaround until I get to check what's going wrong then draining lava. Cheers ,-

Tried this, seems that it also stops working after a while, although I can't exactly pinpoint when. It's rather... Odd, really.

**Comment by stfwi** [comment]
Oky, finally came across tackling this, in `engineersdecor-1.18.1-1.1.20` the device accepts input from other blocks/automation only when the tanks is empty. Cheers,-
