### ISSUE TITLE
[suggestion] covered ladders

### ISSUE THREAD

**Issue by majijn** [stfwi/engineers-decor#2]
like the metal ones from IE, but in wood/treated wood

**Comment by majijn** [comment]
especially if there's a variant with the face opposite the ladder open!

**Comment by stfwi** [comment]
Goes on the whishlist. Taking a look first if other mods have covered this feature already ;)

**Comment by stfwi** [comment]
So I close this, it's on my analog list.

**Comment by majijn** [comment]
analog list?
