### ISSUE TITLE
fluid valve comments 

### ISSUE THREAD

**Issue by majijn** [stfwi/engineers-decor#20]
neat that you're working with fluids!
technically you can do something like the valve with fluid routers, by setting the fluid you're filtering , and then having a fluid youre not using in the input side!

the recipe is neat, but i feel like it may be more fitting to have it use an iron mechanical component as well, or instead of one of the pipes!

as a suggestion , would it be possible for redstone signals to have them not let fluid through when powered? like metal fluid barrels
and maybe crafting one with itself would give the version now that ignores redstone?

they do seem to choke fluid transfer speed, when the pump is rf powered, am i just measuring it wrong/ or is it intended for them to choke fluid transfer? 
![2019-04-28_01 09 04](https://user-images.githubusercontent.com/18368034/56856083-a69cb280-6953-11e9-9b9d-b2683e16460c.png)
set up is on the left is just IE pipes and a metal barrel to act as a choke (only lets 40mbpt iirc,)
middle set ups are using your valve, rightmost is only pipes; they were all enabled at the same time.

![2019-04-28_01 30 58](https://user-images.githubusercontent.com/18368034/56856187-87068980-6955-11e9-8db3-9d01b970a267.png)
adding a metal barrel chokes it even further for some reason? it should have been full, the one with IE pipes was full by the time i took this screenshot
if the choking is intended i withdraw all of that , though =)

the texture is very nice! good work!

**Comment by stfwi** [comment]
Hi, wow - cool details! I'm already on a rs controlled valve, just need to get the connector for redstone right. I'll check about the transfer rates, currently it should forward 1000millibucks per tick. Lets crank that value up a bit for the next beta release ;)

**Comment by stfwi** [comment]
That's the redstone controlled valve ...
![2019-04-28-rsvalve-concept-impl](https://user-images.githubusercontent.com/28822525/56860397-7de9dc80-6996-11e9-83cb-d9e366bbb1b0.png)

**Comment by stfwi** [comment]
Ok I traced the flow rate stuff. I get max 1000mb from the pipes per tick (I set the decl for internal capacity to 10000 for testing). It appears that intrinsically every transition from the IE pipe network to other fluid containers/handlers comes with a choke. Blusunrize has quite a smart piping, he calculates distributions and flows over the whole pipe network. So for the time being let's get the valves running and live with a reduced flow rate.

Receipe: two pipes left/right and one iron mechanical component sounds very good. For the redstone I think connector shapeless with a IE redstone connector should do.

**Comment by stfwi** [comment]
One thing could have helped here - going into the IE code I saw that a "pressurized" tag is set by powered pumps (but removed when going out of a IE pipe network into another block like my valves), so this tag is now forwarded into pipes again. Can you double check if that also helps speeding up your setup?

**Comment by majijn** [comment]
ill give it a look when i get a moment! thanks for the tip!

**Comment by majijn** [comment]
tested it! and it works great! however in some situations it seems to be giving the pressurized tag when the fluid doesnt have it to start with
![2019-05-01_05 08 33](https://user-images.githubusercontent.com/18368034/57004546-1f0fa780-6bd0-11e9-92dd-0432ea026373.png)

edit: seems that putting the valves next to the pump gives it the pressurized tag no matter what

![2019-05-01_06 00 23](https://user-images.githubusercontent.com/18368034/57005258-c7286f00-6bd6-11e9-8103-1374980de2c3.png)

**Comment by stfwi** [comment]
Yes, the pressurized condition comes from the initial flow rate that was put in. In the IE code the flow rate condition is "pressurized ? 1000 : 50 ". So, when I get inputs >50 I assume it's pressurized. I actually need to double check if I only set this when there is a pipe ahead.

**Comment by stfwi** [comment]
So, included in 1.0.4b9 a fluid pipe insertion check, which should now choke the flow rate to the IE default behavior. If this works on your setup, too we could close this issue ;)

**Comment by majijn** [comment]
all seem to be working great from what I can tell! =D

**Comment by stfwi** [comment]
That sounds good! After finishing the pass-through furnace experimental and valve testing with some mods and no further reports it'll be release version with valves then.

**Comment by stfwi** [comment]
Released, so closing this.
