### ISSUE TITLE
Minecolonies incompatibility

### ISSUE THREAD

**Issue by emanuele246gi** [stfwi/engineers-decor#201]
I noticed that there are some rotation issues with Minecolonies and customized buildings, they keep facing the original schematic direction instead of following this specific rotation of the building:
![2022-03-06_14 41 06](https://user-images.githubusercontent.com/61762317/156927747-dcec21c5-182b-4bf7-914a-b47e29df2ae0.png)
Minecraft: 1.16.5
Forge: 36.2.29
Engineer's Decor: 1.1.16
Minecolonies: 1.0.456-BETA

**Comment by stfwi** [comment]
Hi, oky let me take a glimpse what this is ;)

**Comment by emanuele246gi** [comment]
Thank you!

**Comment by emanuele246gi** [comment]
What happened to this issue? It's still in 1.18.2

**Comment by stfwi** [comment]
Hi, I likely have to shift it towards 1.19.x (unfortunately a busy times, and I completely forgot to add the fix to the last release). Good that you pinged the issue.

**Comment by emanuele246gi** [comment]
But I will probably not update my modpack for 1.19 at the moment, versions came out too fast and I didn't finish the 1.18.2 one!

**Comment by stfwi** [comment]
Oky, I tried a quick shot by defining the rotation in my own classes instead of using the default MC block rotation mechanism. Could you take a look at `engineersdecor-1.18.2-1.1.25`? If it's okay I gonna mark that version from beta to release. Cheers,-

**Comment by emanuele246gi** [comment]
Okay I'll see it right now, thank you for all your efforts tho!

**Comment by emanuele246gi** [comment]
![2022-09-24_12 02 19](https://user-images.githubusercontent.com/61762317/192092123-b279325e-28f6-4622-962d-ab649335f904.png)

It doesn't seem to work, those in the right direction were the one I fixed by myself, after the builder finished building

**Comment by stfwi** [comment]
Oky the railings had no rotation implementation at all I just see. I quickly added this in the attached jar, could you take a look (I currently don't have a Minecolonies setup and also would need to dig into the matter of structure definition ;/)?

[2022-09-25-engineersdecor-1.18.2-1.1.26b1.zip](https://github.com/stfwi/engineers-decor/files/9640360/2022-09-25-engineersdecor-1.18.2-1.1.26b1.zip)

**Comment by emanuele246gi** [comment]
I'm trying it right now, also, the issue exists in Gauges and Switches too 😅

**Comment by emanuele246gi** [comment]
Yay! It worked! Thank you man!

**Comment by stfwi** [comment]
Very nice, I'll wait for feedback of another issue an then make a release build. Good that you did into this, I wouldn't have noticed that bug. According to G&S, that's gonna be a bit more interesting - first mod, extended quite from a simple code base, and now due for a refurbishment, that may need some time, even not ported yet to 1.19...  Cheers man,-

**Comment by emanuele246gi** [comment]
Very good, thank YOU for your efforts!
