### ISSUE TITLE
[1.18.1] Cannot pass wire through dark shingle roof wire conduit

### ISSUE THREAD

**Issue by ghost** [stfwi/engineers-decor#202]
Minecraft 1.18.1
Forge 39.1.2
Immersive Engineering 1.18.1-7.1.0-145
Engineer's Decor 1.18.1-1.1.19

As discussed in the Curseforge comments. When attempting to install a wire through a roof wire conduit, the game says "The connection is obstructed." and the wire is not placed.

[Pic of test setup.](https://i.imgur.com/ElsHKvC.png)

**Comment by stfwi** [comment]
Hi BC, thanks for the hint, I'll check the shapes (where I think the problem is) as soon as it is possible. Cheers,-

**Comment by stfwi** [comment]
![image](https://user-images.githubusercontent.com/28822525/159171986-73bcf3c3-a61c-46ce-b6bd-939dcc00b01a.png).

Oky, was a library discrepancy with the collision shape as suspected, fixed is scheduled for the next release ,)

**Comment by stfwi** [comment]
Fix version is `engineersdecor-1.18.1-1.1.20`, it's in approval on Curse. Cheers and ty again for the hint!
