### ISSUE TITLE
Crashes on load [1.18.2]

### ISSUE THREAD

**Issue by freopt** [stfwi/engineers-decor#207]
[crash-2022-04-04_14.15.00-client.txt](https://github.com/stfwi/engineers-decor/files/8412137/crash-2022-04-04_14.15.00-client.txt)

**Comment by stfwi** [comment]
Hi, ty for the hint, think I found it (block reference name incorrect). It's scheduled for the beta2. Cheers,-

**Comment by stfwi** [comment]
Ok, the fix version is up on Curse, cheers,-
