### ISSUE TITLE
Incompatability with "Create Crafts & Additions" (1.18.2)

### ISSUE THREAD

**Issue by TehFoxFire** [stfwi/engineers-decor#208]
Hello, I hope your day is going well.
  I have found an incompatibility with "Create Crafts & Additions"  in that it replaces the "External Heater" from IE with its own "Induction Heater". This causes an inability to use the speed boost from FE in the "Small Laboratory Furnace". 
Would it be possible to either build in support for the "Induction Heater" or allow configuring of what item is needed in the AUX slot?

EDIT: Forge version 40.0.44
Minecraft version 1.18.2
Mod version 1.1.22-b2

**Comment by stfwi** [comment]
Hi Tehfox, dito ;)

That can work already with the current version, for trying it, edit the `engineersdecor-server.toml` (save-games directory), there are the lines

```
#Defines (as comma separated list of full registry names) which items are allowed as external heaters in the Aux slot for powered speed boosting.
furnace_accepted_heaters = "immersiveengineering:furnace_heater"
```

Edit this to:
`furnace_accepted_heaters = "immersiveengineering:furnace_heater,create:induction_heater"`, (I presume the registry name is *`create:induction_heater`*)

Cheers,-
