### ISSUE TITLE
Dropper programming issue

### ISSUE THREAD

**Issue by LesBeans1** [stfwi/engineers-decor#209]
Pretty simple. The dropper treats non-stackable objects as a single item instead of a stack, meaning if you use the droppers options for a higher stack drops, nonstackable items will prevent the system from dropping the item, and inevitably fill up the dropper. A simple fix would be to make the system treat them as a full stack, allowing nonstackable and stackable items to be used at higher speeds

**Comment by stfwi** [comment]
Hi, good idea! I quickly included that in the release builds. Cheers,-
