### ISSUE TITLE
[1.12.2] windows have a missing model when better foliage is installed

### ISSUE THREAD

**Issue by xemnes** [stfwi/engineers-decor#213]
hello
so i have looked at #19 and it seems this wasnt fixed due to lack of response, but im still getting this problem on v1.1.4 and with better foliage v2.3.2
is this at all fixable? ive tried to fix it myself but to no avail, theres nothing in the logs indicating a model or blockstate error.
oh i should also probably mention, my mipmaps are set to 0 in video settings, but if its changed to 1, then the windows look fine.

edit: so i found this https://github.com/octarine-noise/BetterFoliage/issues/193#issuecomment-413705830
im not entirely sure what it means but is this at all helpful to solving the problem? the person states the fix is to increase the mipmapping level, but i dont want to enable mipmapping.

edit2: so ive been playing around with the blockstate again, trying to compare it to the autochisel blockstate
i tried changing the layers to different types, changing transpparent to cutout and mipped cutout to solid just to see what happens and sadly nothing.
the only other difference is that theres inventory and facing variants.
but another weird thing is that enabling mipmapping breaks the autochisel block, which is the reverse of what happens with the window block

edit3: Fixed it!!
https://github.com/stfwi/engineers-decor/blob/1.12/src/main/java/wile/engineersdecor/blocks/BlockDecorWindow.java
line 40 - change CUTOUT_MIPPED to SOLID
then in the blockstates for both
line 8 - change Cutout Mipped to Solid

completely fixes the problem and mipmapping is unaffected also.
since the frame is made of elements with solid textures, it doesnt need to be Cutout or Cutout Mipped

**Comment by stfwi** [comment]
Hi xemnes, wow ty for diving into the matter, let me take a glimpse at the situation. Cheers,-

**Comment by stfwi** [comment]
Oky veery nice work! Quickly installed the 1.12 IDE again and rebuilt/checked the mod. The fix version is pushed to Curse and should be available soon. Cheers man!

**Comment by xemnes** [comment]
youre welcome :D
