### ISSUE TITLE
[Feature Request] A cosmetic link for beam to hang cable or block like the cable anchor from ae2

### ISSUE THREAD

**Issue by kevindery** [stfwi/engineers-decor#214]
A cosmetic link for beam to hang cable or block like the cable anchor from ae2

![2022-05-07_11 04 52](https://user-images.githubusercontent.com/50062694/167260077-2c07e1a3-2be5-4bf9-8a17-832a1631944f.png)

**Comment by stfwi** [comment]
Hi Kevin, let me note this for feasibility checking. Cheers-

**Comment by stfwi** [comment]
{preparing repository archiving}
