### ISSUE TITLE
[1.18.2] Wither can break rebar concrete and panzer glass

### ISSUE THREAD

**Issue by snarkbait66** [stfwi/engineers-decor#217]
Just had a wither break both those items, never had that happen in 1.16.5. This was not during the wither's initial change explosion but after.

Custom modpack, latest version of ed. I don't think I have any mods which alter the wither, except maybe enchantWithMob?

**Comment by snarkbait66** [comment]
it's a tag problem. Your 'tags' folder has an underscore

**Comment by stfwi** [comment]
Hi, sorry about the late response. Aye there have been initial issues with the tagging. I'll check with a contemporary Forge version if I can re-enable the json tags. Cheer,-

**Comment by snarkbait66** [comment]
Thanks! I fixed it for myself in the meanwhile by adding the tags manually in crafttweaker.

**Comment by stfwi** [comment]
Oky, nice, it also works now with the internal mod resources. I pushed the update to Curse, ty again for the hint, I already forgot about this tag problem ;)
