### ISSUE TITLE
[request] treated wood logs

### ISSUE THREAD

**Issue by majijn** [stfwi/engineers-decor#22]
![2019-05-01_06 43 32](https://user-images.githubusercontent.com/18368034/57005958-c8f53100-6bdc-11e9-9f7f-184de6d46a08.png)
 making a debarked log texture with a treated wood look would be really neat, and easier to include in some builds than vanilla logs!

**Comment by stfwi** [comment]
I like to leave these basic material decisions to blusinrize. IE's gonna be there in 1.13 and later, so he may want to add something like this, and a small deco mod should not collide with that.

**Comment by majijn** [comment]
this isnt basic material, its just for aesthetics, i think hazard has made textures for treated logs but they're unused.

**Comment by stfwi** [comment]
It might become basic material then the 1.13 stripped wood logs can be used. Logs with bark are seldom impregnated/treated. I somehow refrain from adding it, intuitive thing. Sorry ;)
