### ISSUE TITLE
[1.19] Forge breaking change causes mod not to load.

### ISSUE THREAD

**Issue by ProsperCraft** [stfwi/engineers-decor#220]
https://gist.githubusercontent.com/ProsperCraft/517507b4fb3d8ba55363d2c087c9352e/raw/338441163bc3db3f9a5d79f228f95f747d4b4a99/gistfile1.txt

**Comment by stfwi** [comment]
Hi Goshen, aye, there were some additional breaking changes announced, I'd like to wait with the update until next weekend - I already updated Redstone Pen in between and it's broken again. We may have to give the Forge Smiths some time to settle things with the new MC version. Craft long and prosper, Cheers,-

**Comment by stfwi** [comment]
Oky, it's on Forge 1.19-41.1.0 now, also pushed on Curse. Cheers,-
