### ISSUE TITLE
factory hopper duping items

### ISSUE THREAD

**Issue by pmytilin1984** [stfwi/engineers-decor#221]
i can reliably dupe charcoal, possibly other items, version 1.1.18 (playing on enigmatica 6 expert)
[2022-07-29 20-01-45.webm](https://user-images.githubusercontent.com/16614257/181810897-a25dc31d-ac3e-44a1-8cb4-533b74f5b3c1.webm)
)

**Comment by stfwi** [comment]
Hi, pmy, thanks for the hint - Let me take a look at this. Cheers,-

**Comment by stfwi** [comment]
E6 reference issue: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/5118.

**Comment by stfwi** [comment]
Made some tests, I may need to take Sveid onboard for help, it looks like compat issue between the two mods. I can't reproduce the problem e.g. with a minecart.

**Comment by stfwi** [comment]
[2022-07-30-test-factory-hopper--tug-latest.log](https://github.com/stfwi/engineers-decor/files/9225799/2022-07-30-test-factory-hopper--tug-latest.log)

**Comment by stfwi** [comment]
Insertion Code:

https://github.com/stfwi/engineers-decor/blob/c6faf7b6fde34b3b709862c78ff9520fb9c4c2af/src/main/java/wile/engineersdecor/blocks/EdHopper.java#L534-L565

**Comment by stfwi** [comment]
Related item handler of the tug:

https://github.com/MuradAkh/LittleLogistics/blob/62ecaf005a0f68604d83cfacce7cbd556d1c9f66/src/main/java/dev/murad/shipping/entity/custom/tug/AbstractTugEntity.java#L129-L166

**Comment by stfwi** [comment]
Alright, sorted out, engineersdecor-1.16.5-forge-1.1.19 is in the approval process on Curse. Cheers,-
