### ISSUE TITLE
[Feature Request] Connectivity for Steel Poles

### ISSUE THREAD

**Issue by ZJDavis** [stfwi/engineers-decor#222]
Can the poles have connections added? Like panes and fences will not connect to the pole. Alternatively a new block that visually connect to other things, but writing in connectivity to fences and panes would be optimal.

Even poles will not connect at right angles to existing poles. There is no corner, 3-way, or 4-way block either.
_edit: the double t beam works for horizontal runs. It seems the poles were not designed for that._

I'm not sure about the level of effort for this

**Comment by stfwi** [comment]
Hi ZJ, yes, the poles are initially designed not to connect to adjacent blocks. Let's leave the FR issue open, I recall that a similar request already dropped in a while ago, so it's at least to be worth to be "triage'ed". Cheers,-

**Comment by stfwi** [comment]
{preparing repository archiving}
