### ISSUE TITLE
[1.18.2] Small Mineral Melting Furnace

### ISSUE THREAD

**Issue by adkinss** [stfwi/engineers-decor#223]
On 1.18.2, the Small Mineral Melting Furnace gets stuck on phase 3 after taking a cobblestone from input, converting it into lava and then the lava is pulled out, leaving the furnace empty.  As long as the furnace stays in phase 3, no new cobblestone is pulled in.  

Breaking the furnace and putting it back resets the furnace back to phase 0, resulting in cobblestone being pulled in.  However, it gets stuck at phase 3 again after turning into lava and the lava being pulled out.

Right-clicking the furnace with a cobblestone in hand does successfully insert the cobblestone and resets the furnace back to phase 0, but the furnace gets stuck at phase 3 again when the lava is pulled out.

This is on the latest version of the mod, 1.18.2-1.1.23.

**Comment by adkinss** [comment]
I am currently using AE2 to import cobblestone on the side, pull lava from the top and power from the bottom.  Just to rule out AE2, I have also put pipes for input/output and I have also tried hoppers (regular hopper and omni-hopper for input, liquid hopper for output).  The behavior is the same across all the different setups.

![image](https://user-images.githubusercontent.com/2963479/183264694-cf9fe0ef-2bba-4497-8344-c55aca0dad01.png)

**Comment by adkinss** [comment]
Using a lever or button on the side allows it to reset back to phase 0.  Putting a redstone clock next to the furnace also allows it to reset when the pulse hits while on phase 3.  However, if the pulse hits while it is in the process of draining the lava, the phase is reset to 0 and any lava not transferred is permanently lost.  Pulsing during phase 1 and 2 doesn't appear to have any negative side effect, other than lengthening the phase a little. 

The current issue is solvable with redstone enhancements, though not ideal.  I use this furnace in about every modpack that has Engineer's Decor in it (love it!), but this is the first time I have used it in a 1.18.x pack and the first time I have had issues with it.

**Comment by stfwi** [comment]
Hi adkinss, thanks for the details, I think I know where to look (fluid tank level->0 on external extraction). Let me quickly double check ;)

**Comment by stfwi** [comment]
Aye, that was it (was also reproducible with IE fluid pipes and pump). Fix version [engineersdecor-1.18.2-1.1.24](https://www.curseforge.com/minecraft/mc-mods/engineers-decor/files/3922673) is pushed to Curse ;).

**Comment by stfwi** [comment]
Fix is released, closing.
