### ISSUE TITLE
Metal Crafting Table can delete held items when closing inventory

### ISSUE THREAD

**Issue by kinlochuk** [stfwi/engineers-decor#224]
Overview:
As the title says, when holding items with the mouse while in the inventory of the metal crafting table, when closing the inventory the items seemingly vanish, and as far as I can tell are destroyed permanently.  

Steps to reproduce:

1. Open the metal crafting table inventory
2. Pick up an item stack from the inventory with the mouse
3. Close the crafting table inventory 
4. Observe the lack of held item stack

Expected outcome:
The item stack should either:

- Return to the inventory (either player or metal crafting table)
- Drop on the floor (in the case there is no space in inventory)

Actual outcome:
 - the items held in the mouse vanish without a trace
 
Effected version(s):

engineers decor-1.18.2-1.1.23

Note: I had other mods installed as well, including JEI and Quark, a full list of these can be provided should the info provided not be enough to reproduce the issue.

**Comment by stfwi** [comment]
Hi kinlochuk, thanks for the hint. I added a bit of code that moves the carried stack back in the player inventory on close. Could to take a look if it's also resolved in your setup and quickly send feedback? Cheers,-

(version engineersdecor-1.18.2-1.1.25 is in approval on curse)

**Comment by kinlochuk** [comment]
> Hi kinlochuk, thanks for the hint. I added a bit of code that moves the carried stack back in the player inventory on close. Could to take a look if it's also resolved in your setup and quickly send feedback? Cheers,-
> 
> (version engineersdecor-1.18.2-1.1.25 is in approval on curse)

Apologies for the delay in getting back to you, I see what I can do :)

**Comment by kinlochuk** [comment]
I have tested with the same collection of mods I had before, and it appears to have fixed it - on my single player test setup before the switch to 1.18.2-1.1.25, closing the inventory voided my held item, afterwar the update when doing the same thing, it put the item back in my inventory, and when I filled my inventory the item instead dropped on the ground all as expected.

Many thanks - I can roll this out to my private server and let my players know to update their client mods :)

**Comment by stfwi** [comment]
Very nice, ty for the feedback. Cheers,-
