### ISSUE TITLE
Misspelling in tooltip

### ISSUE THREAD

**Issue by shrad1994** [stfwi/engineers-decor#227]
![image](https://user-images.githubusercontent.com/96917010/208865188-13abe95c-8d39-4a5d-a5cb-3328e8f6e740.png)
"do"

**Comment by stfwi** [comment]
Hi shrad, thanks for the hint. It's corrected for 1.16.5/1.18.2/1.19.3 and pushed with the next releases. Cheers,-

**Comment by shrad1994** [comment]
Just gonna throw it out there that I love this mod and the aesthetics it adds into the game - definitely in my top 3 favorite mods. Even as a smaller mod it still adds so much character. So thanks!

**Comment by stfwi** [comment]
Hey, ty for the positive feedback ;). The style is strongly entangled with Immersive Engineering (well, ED is made to be an addon for IE, just without a hard dependency) - so the basic theme is by Blu, Hazard, Malte, TG, et al. They're rocking.

**Comment by stfwi** [comment]
Oky, we've fixed that with the last push ;)
