### ISSUE TITLE
Recipetypes

### ISSUE THREAD

**Issue by Tenchu98** [stfwi/engineers-decor#229]
could you add recipe types for the different machines for pack devs?

I am trying to make a pack that removes ore processing from the furnace, but that makes the lab furnace useless since it inherite the recipes from the furnace.

**Comment by stfwi** [comment]
Hi, well, it's actually a furnace, but I can also see the point. Enabling additional recipes could be a useful thing.
Let me take a look how hard or easy it is. In the best case I can refer to the Mojang Furnace Java code with a cloned recipe type and add this to the furnace processing/recipe search before using the normal Furnace recipes. In the worst case it's a hazzzle - let's see what we see ;)

**Comment by Tenchu98** [comment]
I appreciate it, having recipes that are unique yo these blocks would be helpful for my modpack

**Comment by Tenchu98** [comment]
basically I want to remove ores and raw material from the vanilla furnace, make it produce nuggets instead, and then have this furnace produce ingots

**Comment by stfwi** [comment]
Just to keep you in the loop - didn't get to tackle that yet ;;

**Comment by stfwi** [comment]
{preparing repository archiving}
