### ISSUE TITLE
[suggestion] hemp cloth blocks

### ISSUE THREAD

**Issue by majijn** [stfwi/engineers-decor#23]
i cant chisel n bits the jump cushions , and I would like to have blocks of cloth in a similar vein/look as them so chisels and bits maybe having a carpet as well that doesnt check if its on ground so I can have something covering my outside machines that isnt cobblestone or wood, that looks nicer than woolen carpets

**Comment by stfwi** [comment]
Added to my list. I actually also thought a bit about what we could use fabric for. Making a bounce cushion (half slab, enabled with redstone), or window blinds, or sound damping wall elements. Funny enough never thought about pure deco stuff. So, yah, good idea!

**Comment by stfwi** [comment]
Quick ping - not forgotten about this issue, I'm just lacking of really bright design ideas for that stuff.

**Comment by stfwi** [comment]
Let's transfer that to an analog note ;-)
