### ISSUE TITLE
[1.12.2] Dynamic Trees Block Breaker & Tree Cutter Support not Working

### ISSUE THREAD

**Issue by RedRaspberry** [stfwi/engineers-decor#232]
I looked through previous issues and found #52 , so I'm not sure what broke between that version and the current version.
Block breakers and tree cutters will "see" a tree and break it, but once the bottom block is broken the tree just vanishes from the world instantly instead of going through its falling animation or dropping any items. 
Neither debug.log or latest.log show anything when the block is broken.
Tested with a clean install of latest forge (14.23.5.2060) + JEI (4.16.1.301) + Immersive Engineering (1.12.98) + Engineer's Decor (1.1.5) + Dynamic Trees (0.9.29).

**Comment by stfwi** [comment]
Hi Red, let me mark it, but I have to say that 1.12 is already EOL, so only severe bugs like confirmed mod crashes may be fixed. In case something like that comes up in the next months I'll also take a look at this issue. Otherwise it will be closed eventually. Cheers,-

**Comment by RedRaspberry** [comment]
That's understandable. 1.12 is quite old at this point.

**Comment by stfwi** [comment]
Oky I gave it a try today, but already the IDE/jdk (old oracle) deps already slightly increased the R bits of the RGB value of my face tint (can't compile) :). So, let's 1.12 be 1.12 and move on - 1.20's coming soon. Cheers man,-
