### ISSUE TITLE
[Feature Request] {1.19.2} steel floor grating on walls

### ISSUE THREAD

**Issue by KurageAkagami** [stfwi/engineers-decor#233]
I recently saw a base that had vertical bars on the wall and behind some illuminated blocks (See image). I figured that steel floor grating looks almost the same, but sadly are only usable on the floor, as the name suggests. I would be happy if there was a variant for walls as well (vertical bars).

reference image:
![image](https://user-images.githubusercontent.com/130392115/235424794-3a8d5a3c-0f2a-452f-86dd-0107359fe341.png)

image of steel floor grating:
![image](https://user-images.githubusercontent.com/130392115/235424823-ea8e3cef-e6f9-45a1-9a8f-bf6fe87510f9.png)

**Comment by stfwi** [comment]
Hi Kurage, that should be possible. I have already a generic code for horizontally placeable blocks, the model is already there, so mainly a blockstate JSON file would have to be generated with model transformations I think. Gimme a bit of time to think this through. Cheers,-

**Comment by KurageAkagami** [comment]
That would be great! I would really love blocks like that

**Comment by stfwi** [comment]
{preparing repository archiving}
