### ISSUE TITLE
How to use the external heater on the small laboratory furnace?

### ISSUE THREAD

**Issue by Pishonsho** [stfwi/engineers-decor#234]
Hey loving the mod so far, I gotta ask, how do you use the external heater on the laboratory furnace?

I've tried everything on 1.12.2 last update version of the mod, and in the last update of the mod in 1.19.2; nothing has worked.
It would be nice to have some insight on how to set it up.
Sorry for the dumb question, but I've been 1 hour trying to set it up, and searching stuff to no avail.

**Comment by Pishonsho** [comment]
Sorry for that I thought the external heater, was meant to exchange the coal as a heat source, not that it gives the boost, for some reason I understood it the other way, again I'm sorry for that.
Though It would be nice to have a external heater to work with the lab furnace.

**Comment by stfwi** [comment]
Hey Phish, no worries. That actually reminds me that, IIRC, I have to check if the Heater is still needed for the boost and adapt the documentation if not. You may have actually found a bug ;)  
 Cheer’s,—
