### ISSUE TITLE
Clinker Brick Slabs don't work with the Additional Placements mod

### ISSUE THREAD

**Issue by Delfite** [stfwi/engineers-decor#235]
Hi, I've recently discovered that the "Clinker Brick Slab" and it's stained variant don't work with the mod "Additional Placements" slab placement mechanics, yet the "Clinker Brick Stairs" and it's stained variant work just fine with AP's placement mechanics.

AP's placement mechanics working on a Treated Wood Slab
![image](https://github.com/stfwi/engineers-decor/assets/23504262/7a8a58b7-d6e3-48b2-9f55-c2d53f64168e)

AP's placement mechanics working on Clinker Brick Stairs
![image](https://github.com/stfwi/engineers-decor/assets/23504262/9e06d279-c079-4521-96fc-d4557b67b4ea)

AP's placement mechanics not working at all on a Clinker Brick Slab
![image](https://github.com/stfwi/engineers-decor/assets/23504262/2ce8bf58-7587-46f9-8e1f-2cc90c372034)

If you can fix this, then please do. Using vanilla's brick slabs as replacements doesn't work due to how the texture looks next to Clinker Bricks.

**Comment by stfwi** [comment]
Hi, unfortunately this compat issue cannot be fixed without braking existing games. To enable texture variations, the Clinker slabs have to be technically different from vanilla slabs (workaround for a missing vanilla feature). Sorry man; Cheer's, wile.
