### ISSUE TITLE
Crashes on startup with Road Stuff

### ISSUE THREAD

**Issue by brisingraerowing** [stfwi/engineers-decor#236]
Ref: Aero-Tech/roadstuff#4

Not sure which mod is at fault here.

**Comment by stfwi** [comment]
Hi, I checked the logs - something caused a Forge registry not being available when the mod config event was fired. This is strange, as Forge always triggers the registration events first. I may be able to circumvent that issue in the mod handling, but this  would mask the actual problem. My first guess would be to update Forge. Is that problem unique to one installation or do more people have the issue?

**Comment by brisingraerowing** [comment]
There's a couple people on the linked issue. I hit the crash as well.

**Comment by stfwi** [comment]
Sorry about the late response. I'll try to add tackle this on the weekend. Cheer's

**Comment by stfwi** [comment]
Hi, engineersdecor-1.19.2-forge-1.3.29 pushed to curse. I simply fenced the opt-out processing with exception handling in case it is called while the registry is still not set up. The config events are applied multiple times in the process, so no changes are to be expected here.
