### ISSUE TITLE
Signs

### ISSUE THREAD

**Issue by Carvercarver1** [stfwi/engineers-decor#26]
You asked me to make an issue... waiting.

**Comment by stfwi** [comment]
Perfect, here we go. So this issue is basically for moving the details from curse to here where the coding and designing happens. I'll double check some options this evening.
So just for asking, this is the first time you get in contact with modding, or do you already have some background? I ask because I can prepare the internal coding stuff, and post it, and you can start by basically making the the image for the front of the sign, that makes it easier getting started.
I'll also quickly double check how the texture overrides work again, because it's possible to simply throw the image in to a minecraft sub directory, and it will replace an existing one. Then it's also possible to see how it looks in game without compiling java etc.

**Comment by stfwi** [comment]
[resourcepacks.zip](https://github.com/stfwi/engineers-decor/files/3213501/resourcepacks.zip)

**Comment by stfwi** [comment]
Ok, the small zip contains a few files and the directory structure. If you copy the "signs-dev" sub-folder into your minecraft resource pack folder, then you can select it in the MC options. If you change the "sign_danger_texture.png", then you can see how it looks in the game.

When you are happy with it simply drop it in here, I'll do the block registration and that stuff then. You can choose which one of the two we selected ("factory area" and "caution defense system"). As this is a hobby there is no time frame or so, we simply publish when we say it's good. We can also go through multiple refinements, etc.

**Comment by Carvercarver1** [comment]
Good, I'll do the turrets first. Any boundaries? 

No, I do not have any expirience in modding, but I surely can draw some signs. You'd have to adapt it most likely, though

**Comment by Carvercarver1** [comment]
I have an issue sending the image here. I'll sent it on curse in PM.

**Comment by Carvercarver1** [comment]
tst

**Comment by Carvercarver1** [comment]
[tst.zip](https://github.com/stfwi/engineers-decor/files/3218547/tst.zip)

FINALLY. Here you go. My attempt on this.

**Comment by stfwi** [comment]
That looks awesome! There is one small thing that crossed my mind. We have to thing about the people who don't speak/read English. Would it be possible to replace the text with something sign-language-like, or simply remove the text and shift the turret/person minimally to fill the space?

Again - that is a brilliant drawing!

**Comment by Carvercarver1** [comment]
Well... not sure about that, but I suppose you can "collapse" the bottom and the upper part, so it will be rectangular shape sign? Or make two versions, one for the text, and one without

**Comment by Carvercarver1** [comment]
Or, I can try and repalce it with triangular warning sign...

**Comment by Carvercarver1** [comment]
[tst2.zip](https://github.com/stfwi/engineers-decor/files/3218641/tst2.zip)
Removed text

**Comment by stfwi** [comment]
Looks perfect:

![2019-05-25-scrsht](https://user-images.githubusercontent.com/28822525/58365587-e01afc00-7ec6-11e9-8e55-ce2efbc43e22.png).

**Comment by stfwi** [comment]
One important thing I forgot: Which name do you like to be specified in the contributors file?

**Comment by Carvercarver1** [comment]
J. Carver

**Comment by stfwi** [comment]
Done ;) It's staged for the next beta.

**Comment by Carvercarver1** [comment]
Thinking about the next sign, Any choises, besies factory area?

**Comment by stfwi** [comment]
Oh, sorry for responding late, I did not see your last comment. Uhm not sure yet, I am currently doing tests with the factory dropper (it's a bit complex device and needs to be "decomplicated" or made usable), so that the version with your sign can be released.

**Comment by Carvercarver1** [comment]
Very well. Message me when it will be done, or just tell the required sign after you finish with dropper

**Comment by stfwi** [comment]
Hey again, alright I caught up and added a first factory area sign design.  (meaning "general" factory area, simply the typical industry factory plate that everyone knows).

Have no really bright idea what sign to add next (which is the next most important one). If you like to give one a try I add the current png formats as images. Potentially there is also the "mind-the-step" sign that (in the config->experimental feature set), which I did not release because it looks to stupid. If you want to give that one a try - I'm sure it will be better than my scratch ;)

**Comment by stfwi** [comment]
14x14px (leaves one pixel space at the border:
![sign-rect-14x14-bg](https://user-images.githubusercontent.com/28822525/58906158-9ffc1a80-870b-11e9-9eb3-a93328c15958.png)

16x16px (uses full area of a block):
![sign-rect-16x16-bg](https://user-images.githubusercontent.com/28822525/58906173-a7232880-870b-11e9-94e1-8360b6342b39.png)

14x14px triangular: good for warning signs where the space is sufficient to actually draw something.
![sign-triag-14x14-bg](https://user-images.githubusercontent.com/28822525/58906178-ac807300-870b-11e9-9481-3f1a312aea5a.png)

The wood color fill-up at the borders is to prevent rendering problems with optifine, so we can't make these areas transparent.

**Comment by Carvercarver1** [comment]
Basically, I need to do "Watch your step" sign?

**Comment by Carvercarver1** [comment]
Or something I can think of myself...

**Comment by stfwi** [comment]
One of both, your choice ;)

**Comment by Carvercarver1** [comment]
Been gathering ideas for a while. 
First being aformentioned "watch your step", and the next ones are: probably exit/enter signs for mineshafts or buildings; lava/dangerous fluids; sensitive machinery (in case of filters and complicated segments); "angry engineer warning" with somebody tossing a wrench at another person. And I have a little imagination for more... that's all for now

**Comment by stfwi** [comment]
Sounds good, choose one or two among these. Probably enter/exit or fluid warning could be that most people would be interested in. The angry Eng idea actually brought me to something: What do you think about a wrench sign for "workshop/tool room" or so. Could that work out, too?

**Comment by Carvercarver1** [comment]
Maybe this will work afterall... but I'll think on those two signs

**Comment by Carvercarver1** [comment]
This will take longer than usual. I have no free time until 26-th of this month. 

(Also, I have no idea where can I post my own addon for Ice and Fire for Millenaire (mostly folders for custom stuff), I'd like some advices.)

**Comment by stfwi** [comment]
Hi, that's no issue at all, there are no obligations or expectations. The features "don't run away".
Let's make it like this: I close this issue, and when you have a nice idea for a sign, have time, and like to draw something simply open a new issue and attach the image file. Thx again for the defense warning sign, it looks great (I have already changed the backgrounds of other warning signs to your yellow color scheme).
