### ISSUE TITLE
[suggestion] patina'd sheet metal blocks

### ISSUE THREAD

**Issue by majijn** [stfwi/engineers-decor#3]
I really would like patina's copper sheet metal for my builds as windowsills, I was thinking a plain block with a patina'd look would be great in conjunction with chisels and bits,

 but it may be more in the scope of this mod to add the actual patinad sheetmetal blocks and then also copper windowsills?

**Comment by stfwi** [comment]
ok, I'll put it on the whishlist. If you are brave enable the experimental features in the mod config.  Experimented with sheet metal roof - but that looks not releasable to me, so I'll redesign that until it's good enough. It's hard with sheet metals ...

**Comment by majijn** [comment]
the roof is neat! tho i get a weird lighting bug with it, the empty bit of it is dark 
I wasnt expecting it to connect like stairs do when I first started playing with them LoL

**Comment by stfwi** [comment]
Yes, block parameters for the roof are not set yet. First I try to get a model done that looks good enough, then I set the block params. Cheers,

**Comment by stfwi** [comment]
Quick info, I did not forget it ;)

**Comment by stfwi** [comment]
Let me put this on my analog list, I have currently no good looking design idea for that. It occurs to me it's quite hard to change the sheet metal textures in a way they look not dirty but actually colored-corroded.
