### ISSUE TITLE
Config options working incorrectly

### ISSUE THREAD

**Issue by IronPiston** [stfwi/engineers-decor#30]
With "Without tr. wood furniture"=true, and "Without windows"=false, there are still poles in JEI, but not treated wood windows. The poles should be disabled, while the treated wood window should still be enabled.
[engineersdecor.txt](https://github.com/stfwi/engineers-decor/files/3263023/engineersdecor.txt)
![2019-06-06_13 48 48](https://user-images.githubusercontent.com/11603684/59058246-d2b82700-8861-11e9-8bcf-fbb8ce6cde8c.png)

**Comment by stfwi** [comment]
Thx for the report, I'll have a look at the opt-out filter.

**Comment by stfwi** [comment]
Ok, extended the category based opt-outs (without poles, without horizontal supports, etc), and also added two "advanced" option text fields for detailed opt-out/opt-in ("Pattern include" / "Pattern exclude"). Uses registry name wildcard matching like "*steel*,*wood*".

**Comment by stfwi** [comment]
Binary is pushed to curse, could you take a glance when you have time confirm that the issue is solved for you?

**Comment by IronPiston** [comment]
Yeah, the configs seem to work great now. I can disable every item added by the mod, and enable exactly what I want to. Thanks!

**Comment by stfwi** [comment]
Perfect. Thanks for the feedback. I'll schedule this for the next release then.
