### ISSUE TITLE
[Implementation] Two remaining signs

### ISSUE THREAD

**Issue by Carvercarver1** [stfwi/engineers-decor#34]
![pack2](https://user-images.githubusercontent.com/48799631/60176926-4fff0800-9820-11e9-9f78-432344659105.png)
![pack](https://user-images.githubusercontent.com/48799631/60176934-52f9f880-9820-11e9-8977-6b42c9db554c.png)

**Comment by stfwi** [comment]
Hi, cheers, I'll check how it looks in-world about next week.

**Comment by stfwi** [comment]
Hi, included the exit sign in v1.0.10-b1, the other sign looks a bit odd when it is placed in the world (somehow always looks a bit different when as image or as block texture in the game).

Do you know how to override texture-packs for in-game testing (for reproducing)?
Cheers-

**Comment by Carvercarver1** [comment]
Unfortunately, I have no expirience in making texture packs, so I cannot help with that :C 
Still, glad you found the use

**Comment by stfwi** [comment]
Hi John, ... I was playing a bit with the lava/acid-sign picture, and well how to say, would intuitively leave it out for now (can't get it look in-game somehow). Let's close this issue for now and reopen (or open a new) when some alternative ideas pop up. Nonetheless thanks for tackling this and making proposals!
