### ISSUE TITLE
[1.14.3] Server crash - java.lang.NoSuchMethodError: net.minecraft.block.Block.func_200291_n()Lnet/minecraft/util/text/ITextComponent;

### ISSUE THREAD

**Issue by ProsperCraft** [stfwi/engineers-decor#35]
I placed a Treated Wood Crafting Table then clicked to open it.

Sidedness issue?
forge-1.14.3-27.0.25
engineersdecor-1.14.3-1.0.9-b1

**Crash log-**
https://gist.github.com/ProsperCraft/9a29823d011b2e3998a5987fbbd4423d

Debug log-
[debug.log](https://github.com/stfwi/engineers-decor/files/3364386/debug.log)

**Comment by ProsperCraft** [comment]
Crashes on opening the small Laboratory Furnace as well.

https://gist.github.com/ProsperCraft/6c3ceb65274b2f580be4f05fb1b37fd8

**Comment by stfwi** [comment]
Thx Prosper for beta testing. There are still some obfustated methods I use as the mappings are not available yet, I'll have a detailed look at this and try find the cause.

**Comment by stfwi** [comment]
You were absolutely right: Client side method access in the server, problem source: Container GUI name getter. On my dev machine the local server did not complain, so I hope this is fixed.

Could you also double check when you have time and confirm that the issue is solved? thx

**Comment by ProsperCraft** [comment]
Resolved.
