### ISSUE TITLE
[1.14.3] Breaking things drops them instantly and doesn't give you the item.

### ISSUE THREAD

**Issue by ProsperCraft** [stfwi/engineers-decor#36]
Signs don't seem to have hardness they break instantly using your first, or an axe.

And you don't get the sign back when it breaks.

Straight Thin Steel poles as well.

Straight Treated Wood pole as well.

**Comment by stfwi** [comment]
Same here, thx for reporting!

**Comment by stfwi** [comment]
There's something going on with the block drops in Forge. I added a hotfix until this is sorted out.

**Comment by ProsperCraft** [comment]
resolved.
