### ISSUE TITLE
[1.14.3] Metal rung ladder recipe conflicts with vanilla minecart.

### ISSUE THREAD

**Issue by ProsperCraft** [stfwi/engineers-decor#37]
![f517d4dc853eeee05ebae1eca29c11ca](https://user-images.githubusercontent.com/4427684/60751640-13e14b00-9f76-11e9-8da1-a8ea995fed38.png)

**Comment by stfwi** [comment]
Oh man, blindness caught me! That are also the alternative recipes for 1.12.2 if IE is not installed.

**Comment by stfwi** [comment]
Ok, fixed in `v1.0.9-b2-mc1.14.3`, `v1.0.10-b1-mc1.12.2`.

**Comment by ProsperCraft** [comment]
Resolved.
