### ISSUE TITLE
[1.14.3] blocks don't drop when broken.

### ISSUE THREAD

**Issue by ProsperCraft** [stfwi/engineers-decor#39]
Staggard metal steps, treated wood ladder, and Metal rung ladders.

Prolly related to the forge issue/change you mentioned before.

Modpack -https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by stfwi** [comment]
I might have forgotten the hotfix in these ... should be fixed quickly.

**Comment by stfwi** [comment]
Well, had to be a more general fix, so all block drops are now organized in the mod itself.

**Comment by stfwi** [comment]
engineersdecor-1.14.3-1.0.9-b3.jar is pushed on Curse for integration testing.

**Comment by stfwi** [comment]
Can you, when time, double check and confirm that the issue is resolved in your setup? Cheers -

**Comment by ProsperCraft** [comment]
Verified fixed.
