### ISSUE TITLE
[1.14.3] Feature request, flower pots that sit on the sill.

### ISSUE THREAD

**Issue by ProsperCraft** [stfwi/engineers-decor#40]
![2019-07-06_15 00 38](https://user-images.githubusercontent.com/4427684/60761099-13d95d80-9fff-11e9-95ce-5f2dbfeffe40.png)

**Comment by stfwi** [comment]
My first design of the sill had a broader board. It looked quite off, so my decision was to shorten it, knowing that it's not possible to place things on it as blocks. 
My "master plan" is to make random decorations on it when placing, similar to paintings. But other things first. 
So I close this issue with "won't fix", an alternative is on the todo list.
