### ISSUE TITLE
World Loading Issue

### ISSUE THREAD

**Issue by TheOhmegha** [stfwi/engineers-decor#42]
I recently installed the Engineer's Decor mod along with various other mods such as the SecurityCraft mod, the JEI mod, Mr. Crayfish's Furniture Mod, etc. I had a world loading issue in which when I joined my world, everything was gone. I left my world open for five hours and nothing appeared. So I deinstalled each of my mods and opened a backup world to see if the world would load. It did...when I deleted the Engineer's Decor mod. I'm not sure why but this is an issue that needs to be addressed.

**Comment by stfwi** [comment]
Hi, I agree, this has to be addressed. Let's quickly go through - To analyze the problem I need some data about what was installed and what happened:

- Could you tell which version of the mod and Minecraft you had installed (the file name already contains the version, e.g. "engineersdecor-1.12.2-1.0.9-b3.jar" is for MC1.12.2, mod version 1.0.9-b3).

- Very helpful would be the log files where the problem occurred, you can find it in the ".minecraft/logs" folder. Simply drop it into this thread for uploading.

Cheers -

**Comment by TheOhmegha** [comment]
The version was engineersdecor-1.14.3-1.0.9-b6.jar. I updated to this
version today after I was using the one from this website (who's version
also had the same issue. I'm not sure which version it was but this version
from this website is the original source. The latest version on the
CurseForge website still has this issue.) The log will be attached to this
email.

**Comment by stfwi** [comment]
Ok, 1.14 contains still a few surprises. The problem was apparently that fluid handling is not yet tackled in Forge (or changed and I have it wrong now, needs check). As a hot-fix I disabled the fluidics functionality of valves and the Fluid Accumulator, and uploaded `engineersdecor-1.14.3-1.0.9-b7.jar` with this fix.

Could you double check if the problem is also solved on your machine? Cheers -

**Comment by TheOhmegha** [comment]
It’s working now. I guess that you’ll fix the accumulator then?

**Comment by stfwi** [comment]
Naturally. I think it's solvable in the next time. So I close this issue then. Thanks again for letting me know. Cheers-

**Comment by TheOhmegha** [comment]
Btw. I noticed that when I place either of the steel poles, the steel
heads, and the caution really dangerous sign, they appear to be the pink
and black checkered tiles. Is there a way to ofix this? I can't destroy the
block. I know what this issue is but I was wondering if you know how to
destroy these blocks.

**Comment by stfwi** [comment]
Hi, the Forge blockstate files have changed, and I had to update the model paths in them. If you update Forge it should be solved.

**Comment by TheOhmegha** [comment]
Update Forge? To 1.14.4?
