### ISSUE TITLE
[1.14.3] Texture for the Treated Wood crafting table missing.

### ISSUE THREAD

**Issue by ProsperCraft** [stfwi/engineers-decor#43]
engineersdecor-1.14.3-1.0.9-b6

![2019-07-19_12 59 56](https://user-images.githubusercontent.com/4427684/61558821-577f8e80-aa25-11e9-96f8-78a5a752dacf.png)

**Comment by ProsperCraft** [comment]
![2019-07-19_13 03 13](https://user-images.githubusercontent.com/4427684/61558919-9f061a80-aa25-11e9-9486-ecaceb4c893b.png)

**Comment by ProsperCraft** [comment]
Not limited to the table-
![2019-07-19_13 05 34](https://user-images.githubusercontent.com/4427684/61559021-eee4e180-aa25-11e9-9557-5f6d02dca2d5.png)

**Comment by stfwi** [comment]
Hi, I'll look into this asaigt.

**Comment by stfwi** [comment]
Ok, so the Forge blockstate model locations have to be prefixed now like in vanilla, which is good. Unfortunately I had that not changed that yet, and with updating Forge the effect occurred.

Uploaded `engineersdecor-1.14.3-1.0.9-b7.jar` with the corresponding fix.

**Comment by ProsperCraft** [comment]
Verified fix.
