### ISSUE TITLE
Issue with loading with latest forge 1.14.4 28.0.72.

### ISSUE THREAD

**Issue by ovingiv** [stfwi/engineers-decor#49]
[Paste.ee](https://paste.ee/p/lix0V)

**Comment by stfwi** [comment]
Gonna look at the weekend, seems something changed in the recipe conditions interface.

**Comment by LlubNek** [comment]
same thing here with forge .75
Building gadgets has the same problem ( https://github.com/Direwolf20-MC/BuildingGadgets/issues/355 )
[crash-2019-08-30_18.55.54-client.txt](https://github.com/stfwi/engineers-decor/files/3561784/crash-2019-08-30_18.55.54-client.txt)
[latest.log](https://github.com/stfwi/engineers-decor/files/3561785/latest.log)

**Comment by stfwi** [comment]
Hi, thx for the additional info, the recipe conditions api has changed, Direwire and me need to adapt ;)

**Comment by stfwi** [comment]
Ok, problem, the new recipe conditions don't pass me the recipes for condition testing, so we might very well need a change in the Forge - I need to know the recipes to check (!?).

**Comment by ProsperCraft** [comment]
Same with Forge .81
https://gist.github.com/ProsperCraft/a0d27d5923adf3571d8db257f55d8fec

Reproduced with only Engineers Decor.
[debug.log](https://github.com/stfwi/engineers-decor/files/3563497/debug.log)
[latest.log](https://github.com/stfwi/engineers-decor/files/3563498/latest.log)

**Comment by stfwi** [comment]
Hey guys, thanks all for the data! I pushed engineersdecor-1.14.4-1.0.11-b3.jar, which is updated to Forge 81. Whoever made this change in Forge - it is cleaner now, I just had to understand it first ;)

**Comment by stfwi** [comment]
Is this issue still unresolved with Forge 1.14.4-28.1.10?

**Comment by ovingiv** [comment]
Let me download it and I'll update you.

update: I'm currently going through just trying to get it to start. I also downloaded your Redstone mod as it looks really cool.

update 2: Yes, with the current forge and your mods, they all work! @stfwi
