### ISSUE TITLE
[suggestion] leadlight glass and panes

### ISSUE THREAD

**Issue by majijn** [stfwi/engineers-decor#5]

**Comment by stfwi** [comment]
Thx for the input, have window glass already on the list, leadlight is lead but a bit out of scope for the industrial building styles ;-). Making a note that the window panes materials could be varied.

**Comment by majijn** [comment]
by leadlights I mean glass that is held together by lead that is melded together in a frame!
![967433096](https://user-images.githubusercontent.com/18368034/53249482-79642780-36b8-11e9-9738-6f7df7e3e35c.jpg)
like these

sorry for lack of further explanation I had to send this quickly on my phone before I forgot about the request =)
