### ISSUE TITLE
[1.12.2] Enhancement - Factory Dropper

### ISSUE THREAD

**Issue by grundyboy34** [stfwi/engineers-decor#51]
I'll start off by saying the Factory Dropper is absolutely amazing, well done!
However it seems to have one shortcoming, and that is it only detect pulses for the redstone signal.

For example, I set the filter to a few items, and set both options to use AND. The block already uses an internal timer it seems, so I would expect that putting a redstone torch beside of it would cause it to constantly drop as long as the filter parameters were met, but instead it drops once when the torch is placed and then stops.
This is in contrast to setting the filter to AND, and the redstone to OR, which constantly drops as long as the filter is met.

[Suggestion]
 So, as to prevent misunderstandings and to not limit options, could it possible to have another gui option to swap the redstone detection between pulse and hold modes? So that in hold mode, a constant signal drops using the internal timer rather than waiting for another pulse.

**Comment by stfwi** [comment]
Hi Aristine, thanks for the feedback. 
Aye, the filter trigger counts as internal frequent pulse source that shall allow to drop all stacks in defined in the filters. The external redstone source shall have the pulse aspect of the vanilla dropper or dispenser. Timing and stack settings are to ensure the Factory dropper does not operate too fast. 
The dropper is also intended to be used with timing contraptions around it. I use the Interval Timer of my Gauges and Switches mod for this.

There is a known issue I need to tackle though: in OR->AND combination it does not drop non-matching stacks on redstone pulse, this should be fixed.

Would the external interval timer be a solution for you?
![2019-09-09_18 34 37](https://user-images.githubusercontent.com/28822525/64549301-baf4b100-d330-11e9-87f2-f2cd3e15c4d0.png)

**Comment by grundyboy34** [comment]
Yeah I had to end up using a redstone timer from Immersive Tech as I sometimes needed the timer (and dropping) to stop.
If you were to add a hold mode option, it would remove the need for an external timer.
Mostly the reason I thought this is because the little light in the GUI that lights up when an external redstone signal is applied goes into the little circuit diagram, so I expected setting that to and would let it keep going while the light was on.

**Comment by stfwi** [comment]
That's right. I'll see how I can change the behavior without messing up the existing contraptions.

**Comment by stfwi** [comment]
Hmm, from a consistency point of view, would it be comprehensible if the Dropper works in pulse mode if the delay time is zero, otherwise continuous mode? Then I would change the trigger symbol depending on that, lika so:
![2019-09-09_21 07 02](https://user-images.githubusercontent.com/28822525/64559560-df5b8800-d346-11e9-9676-b20098425008.png)

Idea?

**Comment by grundyboy34** [comment]
That could work although the fastest setting meaning pulse wouldn't be very intuitive. 
But, if you don't wanna make a separate button, it's a good option I think.

Another option would be to just make that bottom right icon (trigger button I think you call it) a toggle for the mode and change the icon as such, but that too doesn't make too much sense in the logic gate part of things.

**Comment by grundyboy34** [comment]
On the same note, it probably just needs to be a toggle button above the little redstone signal button (with the down arrow).
I'm sure some people still may need the timer while in pulse mode.

**Comment by stfwi** [comment]
Aye that's a good option.

**Comment by stfwi** [comment]
Ok, the change was small enough to squeeze a first shot in the actual beta, the file is also on curse now (engineersdecor-1.12.2-1.0.12-b1.jar). Can you play a bit with the device for additional testing and quickly write if that solves the issue? Cheers -

**Comment by grundyboy34** [comment]
Thanks for the update! I just gave it a go and it seems to work great. Seems to be able to work the old way, and the new continuous mode seems to work great!

**Comment by stfwi** [comment]
Perfect, glad that it worked out. Thanks again for the trigger button proposal, when testing I already noticed it adds a lot of value! I close the issue then. Cheers -
