### ISSUE TITLE
[Mod Support Request] Dynamic Trees for Cutter

### ISSUE THREAD

**Issue by Voxel-Friend** [stfwi/engineers-decor#52]
Would it be possible to allow the small tree cutter to work on the dynamic tree's mod, and addons for it? I imagine it wouldn't be too difficult.

**Comment by stfwi** [comment]
Hi, I'll double check how this can be done.

**Comment by stfwi** [comment]
Hacked it into the actual beta. Could you also take a look if it does work on your machine? Should chop dytrees of radius 7 or higher.

**Comment by stfwi** [comment]
The cutter is already out a while, I'll close this then ;)

**Comment by Lordician** [comment]
The compatibility seems to work fine, but sadly, only for the Dynamic Trees mod only.
Can you perhaps make it so that Dynamic Trees from compatibility add-ons (like for BoP, thaumcraft and the ones included in Rustic) are also detected?

(Do i need to open a new issue for this?)

**Comment by stfwi** [comment]
Hi, no that's ok, I reopen this one.

**Comment by stfwi** [comment]
Hmm. Ok I have a namespace check for dynamic trees that is likely not needed. Didn't even know that there are compat mod for that. So in the next beta I'll remove that namespace check and we'll see if that applies correctly to the compat mods.

**Comment by Lordician** [comment]
Will keep my eyes on the next beta and i will try to report back my findings.
Thanks in advance!

**Comment by Lordician** [comment]
Seems to work fine in the beta build (engineersdecor-1.12.2-1.0.15-b2).
Thanks!

**Comment by stfwi** [comment]
Perfect that, thx for double checking so quickly. So I'll close this one then.
