### ISSUE TITLE
[Mod Support Request] Wood Cutter doesn't work with menril saplings from Integrated Dynamics

### ISSUE THREAD

**Issue by Federsavo** [stfwi/engineers-decor#54]
Wood cutter cuts only one wood block as seen in the image.

![2019-10-18_19 19 39](https://user-images.githubusercontent.com/29519894/67114756-f068a600-f1dc-11e9-9332-9867076a28ea.png)

**Comment by stfwi** [comment]
Hi, let me take a look at this, currently I have no clue why - because if the tree broken block would not be detected as wood log, then the cutter would not have broken it. The log detection for the tree felling algo is the same however.

**Comment by stfwi** [comment]
Ok I double checked with that, the menril wood has different block types registered. They look the same, but to the program these are different woods. So my tree contour finding algorithm aborts. 
I need to go deeper into the wood matching to find out how to make that with good performance and covering the Menril compat. May take a bit until I tackle it.

**Comment by stfwi** [comment]
Just to keep you in the loop, I did not forget this issue, just don't have an idea what it could be.

**Comment by stfwi** [comment]
Yay, initialize your oredict lookups and behold it works. I also added that the filled Manril is detected as normal Manril, so it should always cut the whole trees:

![2019-11-03_10 54 39](https://user-images.githubusercontent.com/28822525/68084515-ef6b8180-fe36-11e9-9770-b2239ecea85b.png)

**Comment by Federsavo** [comment]
Awesome!
I will let you know if it works to my end when the full udate realeses.

**Comment by Federsavo** [comment]
It works perfectly now, thanks.

**Comment by stfwi** [comment]
Perfect, one closed one to go ;)
