### ISSUE TITLE
[1.14] Error during the load_registries

### ISSUE THREAD

**Issue by cybercat5555** [stfwi/engineers-decor#55]
Engineer's Decor 1.14.4-1.0.15-b1
Forge 28.1.10

When trying to load the game, I get this issue. No crash report is created, but I can include the latest.log

![Screenshot 2019-10-26 14 47 10](https://user-images.githubusercontent.com/17956808/67624543-b95b4b80-f7ff-11e9-90bf-81d85ec22589.png)
[latest.log](https://github.com/stfwi/engineers-decor/files/3775161/latest.log)

**Comment by stfwi** [comment]
Hi, can you please update to at least Forge 28.1.68 and try again with this one? There were some deprecated functions in between, and I implemented the changes accordingly.

Could you quickly reply if it worked with Forge 28.1.68 (then I will add a min-forge-version requirement in the next mod version). Cheers -

**Comment by cybercat5555** [comment]
Yep, after updating it worked

**Comment by stfwi** [comment]
Ok, perfect that, thx for pinging back, I'll add the forge version requirement then.
