### ISSUE TITLE
Treated Wood Crafting Table & Thaumcraft

### ISSUE THREAD

**Issue by DracoShadow** [stfwi/engineers-decor#56]
I've noticed an issue with the table and Thaumcraft. If the crafting grid contains vis shards and you shift click in another type, if it isn't a full stack it will convert it to and add it to the stack in the table. It does not do this if it's in the table's storage slots.

**Comment by stfwi** [comment]
Ok, unfortunately Thaumcraft is closed source so I am not sure, but I have a suspicion what it could be and add an explicit double check for the damage nbt data to the stack matching. Will be in the next beta.

**Comment by stfwi** [comment]
Ok, pushed the beta on curse (stupidly forgot to reference the issue in the commit message).

**Comment by DracoShadow** [comment]
Looks "fixed" to me, though I can't shift click in anything to the grid with NBT data now. Dunno if that's intended.

**Comment by stfwi** [comment]
Hi, ok, that sounds good. I blocked auto-moving stuff with NBT, except "Damage", so that enchanted items or non-empty crates etc are accidentally moved. I close this issue then -
