### ISSUE TITLE
[1.12.2] BetterFoliage & Windows

### ISSUE THREAD

**Issue by DracoShadow** [stfwi/engineers-decor#58]
Unfortunately issue #19 seems to be back again, I would've added this onto that one if it wasn't closed and locked. Currently running 1.12.2-1.0.15-b2, but first encountered on 1.12.2-1.0.15-b1.
![2019-11-01_15 03 16](https://user-images.githubusercontent.com/57167950/68059206-d341d600-fcb8-11e9-95dd-66bbbcef6142.png)

**Comment by stfwi** [comment]
Thx for filing, this is a quite tricky one that I am not able to reproduce. The windows are rendered using the combined transparent/solid rendering available in Forge, it is possible that BF somehow renders as "overlay" (or so) in one of these. If I recall correctly mipping had a role in this.
Could you check your graphic settings, if the mipmap level is 1 or higher (not 0)?

**Comment by DracoShadow** [comment]
Ah yes mipping is indeed playing a part, I had it on 0 when I was having the issue, anything higher than that works correctly.

**Comment by stfwi** [comment]
Ok so we have at least a workaround.
