### ISSUE TITLE
[Mod Support Request] Thaumcraft Tree Cutter Compatibility 

### ISSUE THREAD

**Issue by DracoShadow** [stfwi/engineers-decor#59]
Currently the Tree Cutter does not recognize Thaumcraft trees as trees. I'm unsure why as the logs and leaves are properly in the ore-dictionary as logWood and treeLeaves.
![2019-11-02_19 07 39](https://user-images.githubusercontent.com/57167950/68079253-5a1fad00-fda4-11e9-8ec0-1b553b079fc3.png)

**Comment by stfwi** [comment]
Ok, that is not a compat issue but a quite stupid bug - I forgot to initialize the ore-dict based log lookup, should be fixed in the next beta.

**Comment by stfwi** [comment]
First tests ok - as the cutting algorithm focuses on the tree skeleton there are still some issues cutting Greatwood trees completely (there are a whole lot of leaves between the logs). But this is more something that I would call "space for improvement", not an actual bug. So I release this in the current state.

**Comment by stfwi** [comment]
Ok, the beta is on Curse, can you double check and re-open if something does not look right in this matter?
