### ISSUE TITLE
Ladders don't connect with trapdoors

### ISSUE THREAD

**Issue by Forgilageord** [stfwi/engineers-decor#6]
Noticed when I tried to use treated wood ladders in conjunction with treated wood trapdoors from Engineer's Doors. Vanilla trapdoors let you climb them as if they were ladders when they are touching a vanilla ladder, and Engineer's Doors does the same thing, but with modded ladders as well. I don't know if it would be easier to fix it in your mod, or for Engineer's Doors to add compatibility with your ladders.

**Comment by stfwi** [comment]
Hi, quickly double checked. It's a bounding box issue (the vanilla ladder has a wider BB, so you virtually bump your head on the trap door, also happens with vanilla trap doors). Will be fixed in v1.0.1b2. Thanks for telling.

**Comment by stfwi** [comment]
Ok, pushed to the develop branch. That was luckily an easy one to fix ;)

**Comment by stfwi** [comment]
v1.0.1-b2 released.
