### ISSUE TITLE
[Bug] Block placer places oak saplings instead of the sapling in his inventory

### ISSUE THREAD

**Issue by Federsavo** [stfwi/engineers-decor#60]
![2019-11-04_18 54 07](https://user-images.githubusercontent.com/29519894/68145027-22943a80-ff35-11e9-9546-80480dcda119.png)

![2019-11-04_18 54 03](https://user-images.githubusercontent.com/29519894/68145032-245dfe00-ff35-11e9-8346-adb235b3210e.png)

The bug occurs only with vanilla saplings. For other modded saplings (like integrated dynamics saplings) it works correctly.

**Comment by stfwi** [comment]
Argh 1.12 needs metadata, of course. I am sure that diorite will be placed as stone, too. 
Actually for the diorite I should not fix it ;-)

**Comment by Federsavo** [comment]
It seems to work fine in the latest beta. I have tested only with stone variants and saplings, though.

**Comment by stfwi** [comment]
Aye, I also tested with what was installed in my test setup. Let's close the issue for now, if we see something odd we'll re-open it.
