### ISSUE TITLE
[Graphical glitch] Item rendering when dropped

### ISSUE THREAD

**Issue by Federsavo** [stfwi/engineers-decor#61]
![2019-11-08_22 37 47](https://user-images.githubusercontent.com/29519894/68512406-99ed0580-0278-11ea-9c8d-5db21b53b390.png)

Most of the items of the mod seem to compenetrate with the terrain when dropped instead of floating.

**Comment by stfwi** [comment]
Ah y offset for ground display in the model. Thanks for the hint, I had a unification sanatizing proc a while ago, must be related to that.

**Comment by stfwi** [comment]
Ya, also simply forgot to add the model translation. Will be fixed in the next betas.

**Comment by stfwi** [comment]
Ok, jar uploaded to curse.

**Comment by Federsavo** [comment]
Now it is much better.
Just a side question about the block placer: is it supposed to spit out seeds instead of planring them?. If it isn't intentional i will open another issue.

**Comment by stfwi** [comment]
Hi, no if the soil is good for the seed, and the seed is not any modded item with special own handling that cannot be planted, then it's a bug. Let's close this graphic issue and open a new one - in the mean time I'll check what the hack makes this planting action fail ;-)
