### ISSUE TITLE
Placement of gun turret sign caution defense sytem ahead not removable

### ISSUE THREAD

**Issue by themartin1** [stfwi/engineers-decor#62]

**Comment by Angela** [comment]
Ran into this issue as well. If you place a sign on the floor, it places as though it was up against a wall, but the bounding box is on the floor and doesn't match up with the visuals. You can break the sign if you aim at the floor. Same deal with ceiling placement.

**Comment by stfwi** [comment]
Hi, cheers for pinging the issue with some details. I have already fixed it (was a stupid bug introduced when unifying 1.14 and 1.12 sign placement), will be in the next beta.

**Comment by stfwi** [comment]
The fix is pushed on curse now.

**Comment by themartin1** [comment]
Thank you very much!

**Comment by stfwi** [comment]
Perfect, thx for pinging.
