### ISSUE TITLE
feature request: config for RF requirement

### ISSUE THREAD

**Issue by bloche1871** [stfwi/engineers-decor#63]
Could we get a feature to allow the block breaker and tree cutter to require RF to function at all? The current config doesn't seem to allow this. Thanks!

**Comment by stfwi** [comment]
Hi, ok, gonna add it (your FR is the second one about this matter, I had some objections in the first place due to the manual and translations, but that's a solvable thing in the end). I'll try to add it with the next beta.

**Comment by stfwi** [comment]
Ok, jar is on curse.

**Comment by bloche1871** [comment]
Thank you so much!
