### ISSUE TITLE
Placer spits out seeds instead of planting them in the latest beta

### ISSUE THREAD

**Issue by Federsavo** [stfwi/engineers-decor#64]
![2019-11-17_15 57 53](https://user-images.githubusercontent.com/29519894/69009183-48690880-0953-11ea-9a2e-a8210ba3d1ca.png)

**Comment by stfwi** [comment]
Hi, cheers for opening a new issue for this, from your hint before I have implemented a fix, and gonna also see that the device can place cocoa. Will be in the next beta.

**Comment by stfwi** [comment]
Alright, tests with my local server worked, so I pushed 1.0.16-b3 on curse.

**Comment by Federsavo** [comment]
Can confirm it works with both seeds and cocoa.

**Comment by stfwi** [comment]
Ok, I close this issue then. I something comes across we can reopen it. Cheers for double checking on your machine.
