### ISSUE TITLE
[1.14.4] Attempts to overwrite/change/disable recipes fail

### ISSUE THREAD

**Issue by Nachtflame** [stfwi/engineers-decor#65]
Attempted to toggle machines off with config options - Machines no longer show in JEI, but are still craftable, and recipes can be found by looking at uses of any ingredient used to craft them.
Also attempted to overwrite native recipes with Datapack: Custom recipe shows, but native recipe persists (both with same RecipeID)
   Also noticed that unless Datapack recipe matches {namespace}:path/to/file.json exactly, custom recipes don't show at all.
Attempted to disable recipes with CraftTweaker - No Effect

forge-28.1.90
engineersdecor-1.14.4-1.0.16-b4

**Comment by stfwi** [comment]
Hi, aye the config is ported from 1.12, but there are some version differences that I need to work out, and did not work (or do not yet) work entirely with Forge 1.14. In the particular case you noticed the config is available after registration, and so the recipe optouts do not trigger yet. Another thing is the split in server and client config, I have currently commented that out, it did not work properly in the beginning (need to double check that). The device configs should all work, they are set on config change and needed during game runtime.
So - need some double checks with the Forge Pros how the recommended way of recipe optout is in 1.14, but it's on the list.

**Comment by stfwi** [comment]
Ok, fortunately I was enlightened by gigaherz, it's simply bug. Recipes get implicitly reevaluated at runtime. Fix scheduled.

**Comment by Nachtflame** [comment]
okay. :)  Thank you!

**Comment by stfwi** [comment]
Hi, to quickly double check, has the fix worked for you?

**Comment by Nachtflame** [comment]
Yes! Apologies for not replying sooner!
