### ISSUE TITLE
Blocks drop in Creative

### ISSUE THREAD

**Issue by WenXin20** [stfwi/engineers-decor#67]
`Minecraft v1.14.4`
`Forge v28.1.90`
`Engineer's Decor v1.0.16-b5`

Machine blocks, slabs, & concrete slices all drop when broken in creative.

**Comment by stfwi** [comment]
Hi, this is (better said was initially) intended to allow relocating the blocks with contents and settings. But it's not standard, so I will very likely make a conf option for that.

**Comment by WenXin20** [comment]
Is that intended for slabs and concrete slices though?

**Comment by stfwi** [comment]
No, but they are made with the same custom drops because they drop different dependent on the block state. I have implemented the config option, first test seem to be okay, so I can very likely push a new version after a general test this weekend. Cheers again for filing this matter.

**Comment by stfwi** [comment]
Is the issue resolved from your perspective?

**Comment by WenXin20** [comment]
Yes, thanks!
