### ISSUE TITLE
Glass Renders Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [stfwi/engineers-decor#68]
`Minecraft v1.14.4`
`Forge v28.1.90`
`Engineer's Decor v1.0.16-b5`

This mod's glass block renders incorrectly when placed underwater. It displays water flowing down it's sides.

**Comment by stfwi** [comment]
Hi, cheers for filing, I'll have a look what causes this.

**Comment by WenXin20** [comment]
Bluepower glass had a similar issue that I reported at Qmunity/BluePower#498, if that helps any. :)

**Comment by stfwi** [comment]
Cheers, I quickly checked up in the MC code and fixed it already. MJ has a special handling for stained glass in water, so I simply derived from that. 
There is still a thing with the slabs, but it appears that is normal, as the vanilla slabs also show flowing water. Hmm.

**Comment by stfwi** [comment]
Issue also referrs to: https://github.com/MinecraftForge/MinecraftForge/issues/6319.

**Comment by stfwi** [comment]
So I close this one, testing on my machines were okay and no further occurrence seemed to turn up.
