### ISSUE TITLE
BUG 1.12.2 - Block Breakers don't save rotation value

### ISSUE THREAD

**Issue by JimMiningWorm** [stfwi/engineers-decor#70]
Hi,

There is a bug with the Block Breaker in the latest 1.12.2 version (1.0.16). They don't save their rotation setting.

To reproduce, place a block breaker in the world. Use an IE hammer to rotate it so its facing down. Save and Exit the world, then reload and its rotation will have reverted to a default direction (East).

(Love the mod BTW!)

**Comment by stfwi** [comment]
Hey ho, gonna take a look into this - it's strange, as I do not cache any blockstates, so any rotation modification you see should be saved in the chunk data by minecraft as usual.

**Comment by stfwi** [comment]
Ok, took a quick peek - was a simple one, the Breaker is supposed to be only facing in horizontal directions, but the allowed rotations were also vertical. It's fixed and pushed to Curse. Could you double check if the issue is resolved on your machine?

**Comment by JimMiningWorm** [comment]
I just tested 1.0.17-b3. It now saves it rotation value and no longer rotates vertically, so you can close this ticket. 

Although I might have to add a new "Feature request" to allow rotating them vertically (I had a setup in my world using it that way)  ;)

Thanks for your prompt response!

**Comment by stfwi** [comment]
Alright, I'll put it on the FR list. Needs a proper model for up/down facing, but should be possible.
