### ISSUE TITLE
Include modded ores in Crushing Hammer recipes

### ISSUE THREAD

**Issue by Sixdd6** [stfwi/engineers-decor#72]
It'd be super nice to be able to crush ores from other mods, specifically Silents Mechanisms adds copper, tin, zinc, nickel, silver, lead, bauxite, uranium and possibly others. Also Geolosys adds many of these common ores as well. Maybe an array in the config to add ores ourselves would be good too.

**Comment by stfwi** [comment]
-> Can we redirect this issue to the Engineer's Tools repository, the crushing hammer is implemented there? (for proper issue tracking).

--- 
As quick answer: If this is on 1.12 the recipe should be auto detected, so should basically work for all recipes that take one "ore" and result in two "dust" units.
For 1.14/1.15 I have no proper solution for an oredict replacement yet.

**Comment by Sixdd6** [comment]
Sorry, I should have specified. Yes I did mean for 1.14/1.15. I have tried to use crafttweaker to achieve this goal but it is not yet full-featured. I'll eagerly await your solution then.

**Comment by stfwi** [comment]
Actually, as a temporary solution (or maybe it is now supposed to be done that way for mod-compat recipes?) you can make a server data pack with the needed ore-to-grit recipes. For the Crushing Hammer I use a special recipe type `engineerstools:crafting_extended_shapeless`, allowing to define a tool that is damaged and stays in the crafting grid. The tool is the Crushing Hammer.

This is how the Iron/Gold grit recipes of the mod look like:

```
{
  "conditions": [
    {
      "type": "engineerstools:optional",
      "result": "engineerstools:iron_grit", <<< result item: The recipe is disabled if it does not exist.
      "requires": ["engineerstools:crushing_hammer", "minecraft:iron_ore"] <<< source items: The recipe is disabled if one of them does not exist.
    }
  ],
  "type": "engineerstools:crafting_extended_shapeless",
  "group": "grit",
  "ingredients": [
    {
      "item": "minecraft:iron_ore"             <<< source ore: Same as in the condition
    },
    {
      "item": "engineerstools:crushing_hammer"
    }
  ],
  "result": {
    "item": "engineerstools:iron_grit",        <<< result dust: Same as in the condition
    "count": 2
  },
  "aspects": {
    "tool": "engineerstools:crushing_hammer",  <<< leave this
    "tool_damage": 10                          <<< maybe increase this if the ore is hard to crush?
  }
}
```

**Comment by stfwi** [comment]
I moved this issue to https://github.com/stfwi/engineers-tools/issues/6.
