### ISSUE TITLE
1.15.1 server

### ISSUE THREAD

**Issue by hitsu420** [stfwi/engineers-decor#73]
hey, engineer's decor seems to be crashing on my 1.15.1 forge server, even though it works just fine for the client

crash report: https://hastebin.com/qidihivoku.coffeescript
log: https://hastebin.com/iloqaqicun.md

a thing i did notice though, was that using it in single player in 1.15.1 didnt render items ontop of the custom crafting table. it also said something about 'EntityRender' in the log, I guess that's about where the problem lies?

**Comment by stfwi** [comment]
Hi, the TER rendering is disabled yet in 1.15 (missing some mappings), so the crafting table does not render yet. It seems that the import of a client only class already makes trouble here - the renderer itself is declared client-only. I gonna experiment a bit to get to the bottom of this.

**Comment by stfwi** [comment]
Ok, quickly peeked into the code, forgot a dist marker for a function. The new jar is on Curse (in review, should take not more than 1h).
Could you quickly confirm and close if the issue is solved on your server?

**Comment by hitsu420** [comment]
Great job fixing!
