### ISSUE TITLE
[1.12] Placer doesn't plant sweet berries from the mod "Future MC"

### ISSUE THREAD

**Issue by Federsavo** [stfwi/engineers-decor#75]
![2020-01-03_17 09 42](https://user-images.githubusercontent.com/29519894/71734480-5a8fff00-2e4c-11ea-8e76-f09de87e2c5a.png)

I don't know if I have to submit the issue to you or to the future mc's creator

**Comment by stfwi** [comment]
Hey man, thanks for keeping filing issues for stuff you see! I made a PR for FutureMC, which should solve the issue. The placer looks at an aspect of the item, which says that it can be planted, and what the plant is. That's what the berries need.

**Comment by Federsavo** [comment]
Thank you for maintaining this beautiful mod. Btw I won't close this issue because I see you linked it to the future mc github.

**Comment by stfwi** [comment]
Ok TDC is changing the FMC code to Kotlin (therefor PR rejected) and will implement IPlantable then in Kotlin.

**Comment by thedarkcolour** [comment]
IPlantable is already implemented in BlockBush, which my block extends. I don't know what's happening here.

**Comment by stfwi** [comment]
Hi, sorry I placed my answer not here but in the PR thread here https://github.com/thedarkcolour/Future-MC/pull/87#issuecomment-571480334.
It's about the plantability of `class ItemBerry extends ItemFood implements Modeled` -> `class ItemBerry extends ItemFood implements Modeled, IPlantable`
