### ISSUE TITLE
Misnamed block [engineersdecor-1.15.1-1.0.18-b2]

### ISSUE THREAD

**Issue by Riverstar907** [stfwi/engineers-decor#76]
Just a heads up - The "slag brick stairs" are misnamed as "clinker brick stairs". There are now two instances of the clinker brick stairs because of this in 1.15.1/Forge 30.0.26/engineersdecor-1.15.1-1.0.18-b2
This makes searching by name for it in vanilla or JEI a bit of an inconvenience. 
Thanks for an awesome mod!

**Comment by stfwi** [comment]
Hi, thanks for the hint, gonna fix it in the next beta. Cheers -

**Comment by stfwi** [comment]
Ok the jar is now available on Curse.
