### ISSUE TITLE
[1.12] Tree cutter doesn't respect the config of needing power to run

### ISSUE THREAD

**Issue by Federsavo** [stfwi/engineers-decor#77]
(Sorry for always bothering you ahahah)
I have the config of the tree cutter needing power set on true but even without power it still cuts after a while.(The animation of cutting isn't playing)

![2020-01-08_20 07 47](https://user-images.githubusercontent.com/29519894/72008160-81d33b80-3253-11ea-87cb-d8878cc2a8f7.png)

**Comment by stfwi** [comment]
You're not bothering, an issue is an issue no matter who sees it first ;). I could not resist to take a quick peed into the code and - tada - forgot to decrease the progress when not powered. I probably did not wait long enough when testing the config option. Basically all versions (1.12/1.14/1.15) are affected by that. So will be again a trio-update soon.
