### ISSUE TITLE
Engineer’s Clothing [Feature]

### ISSUE THREAD

**Issue by brisingraerowing** [stfwi/engineers-decor#80]
I would like some clothing for engineering use (steel-toed boots, hard hats, high-vis vests, etc). Would be good for immersion. This might be better as a separate mod, though.

**Comment by stfwi** [comment]
Hi, ya, in this mod I would like to stick to things that help building nice looking factories and buildings for the theme. It will get overloaded if too much different stuff is added. Armor and outfit would be either something for Immersive Engineering or the Engineer's Tools mod if Blu has no plans to add something similar. I'll make a side note in my local todo.
