### ISSUE TITLE
Factory Hopper Unable to Insert in Empty Storage Drawer

### ISSUE THREAD

**Issue by NielsPilgaard** [stfwi/engineers-decor#84]
Hello!

I have a slightly weird mod interaction issue for you: The Factory Hopper is unable to insert items in an empty Storage Drawer, but there is no issue when the Storage Drawer already contains the item the Factory Hopper is pushing.
A vanilla Hopper can insert regardless of existing items.

Is this intended? :)

### Versions
- engineersdecor-1.14.4-1.0.19-b1
- StorageDrawers-1.14.4-6.0.5

Original issue: https://github.com/NillerMedDild/Enigmatica4/issues/284

**Comment by stfwi** [comment]
Hi Niller, no that is not intended ;), likely it's a last-free-slot iteration issue of the "smart" insertion (I try ti fill up existing item stacks in an inventory first and, if all stacks are full or none matches, insert into a free slot). I gonna chase this issue at the weekend and probably push a fix Sat or Sun. Cheers -

**Comment by stfwi** [comment]
Yeah the insertion was confused, I added a simple "dump" insertion run after "smart inserting", which seems to have solved the issue:
![2020-02-06-001](https://user-images.githubusercontent.com/28822525/73927937-93e7de80-48d2-11ea-8469-1b91ed7d239e.png)

Depending on how I get additional testing time I'll push tomorrow or this weekend.

**Comment by NielsPilgaard** [comment]
Awesome, thanks.

**Comment by stfwi** [comment]
Ok, earlier than expected I could push the file to curse.

**Comment by stfwi** [comment]
Ok, the parent issue has been closed, I presume the fix is approved.

**Comment by NielsPilgaard** [comment]
Ah yes the fix is approved! Sorry I forgot to get back to you.
