### ISSUE TITLE
[1.15.2] The + to add the recipe from JEI in to the Treated wood crafting table is missing.

### ISSUE THREAD

**Issue by ProsperCraft** [stfwi/engineers-decor#85]
The + to add the recipe from JEI in to the Treated wood crafting table is missing.

engineersdecor-1.15.2-1.0.19-b1

![2020-02-04_22 27 13](https://user-images.githubusercontent.com/4427684/73813628-c47a2c00-479d-11ea-80c1-8c7f35ee0fe4.png)

**Comment by stfwi** [comment]
Hi Goshen - thx for the hint! The JEI integration is already implemented, I had to disable the ref it in the build script in the beginning because the API was not out yet. I'll double check and recompile if it's accessible now. Cheers -

**Comment by stfwi** [comment]
Ok, version is up on curse. I close the issue directly as it was no bug that needs additional double checks or approvals I think. Cheers again for the hint!
