### ISSUE TITLE
Treated Wood Table - DUPE Bug

### ISSUE THREAD

**Issue by Nachtflame** [stfwi/engineers-decor#87]
Currently, anything normally stackable, that is differentiated by .nbt (Treated Wood tables with contents as example) can be duplicated by placing such an item with contents in the grid/storage of these tables, and shift-clicking any number of others into the same stack.
 Checked across multiple versions of the Mod for 1.14.4, as well as 1.15.2

**Comment by stfwi** [comment]
Alright, thanks for that hint! Just in case you wanna laugh a bit: I had to fix that also for the Hopper, both Furnaces, the Milker, the Waste Incinerator, and the Dropper ;-). Porting Item equality glitch.

**Comment by stfwi** [comment]
Alright, the fix is approved on curse. Could you double check and close the issue if it's okay on your setup? Cheers -

**Comment by Nachtflame** [comment]
Thanks much!
