### ISSUE TITLE
[Request] Add block/item tags to stairs, slabs, and walls

### ISSUE THREAD

**Issue by ghost** [stfwi/engineers-decor#89]
Hello. I've noticed the tags for slabs, stairs and wall blocks of the mod aren't setup, because of that it's not possible to use the Create mod's "glass panes in slabs/stairs" feature due to them missing the tag entries.

since the minecraft/forge subfolders aren't present in the mod's data folder I've included a 
simple folder setup for the tag locations & JSONs as a example below:
```
data/minecraft/tags/blocks/slabs.json
data/minecraft/tags/blocks/stairs.json
data/minecraft/tags/blocks/walls.json
data/minecraft/tags/items/slabs.json
data/minecraft/tags/items/stairs.json
data/minecraft/tags/items/walls.json
```
As for the JSON files, I've added the files to a zip below.
All 3 are for both of the blocks/items subfolders.

[MissingTags.zip](https://github.com/stfwi/engineers-decor/files/4239841/MissingTags.zip)

**Comment by ghost** [comment]
I forgot to mention: This request is for version 1.14.4 of the mod. But it could also be applied to other versions if needed.

**Comment by stfwi** [comment]
Hi, thanks for the hint, it's very cool that you already prepared the data. I'll try to include it in the next beta (scheduled for tomorrow evening (UTC) if I can time it and no blocker pops up during the tests).

**Comment by stfwi** [comment]
Ok, your data is up and approved on Curse with the new mod version `1.0.19-b4` in 1.15.2 and 1.14.4. Could you double check if that is all correct as intended and close the issue if so? Cheers, wile -

**Comment by ghost** [comment]
Much appreciated, thanks!

EDIT: The data appears to be setup correctly and working fine aswell. glass panes can be inserted inside stairs and slabs with Create now. apologies for the rushed comment.
