### ISSUE TITLE
[1.12.2] Disabling Signs does not remove Sign Plate

### ISSUE THREAD

**Issue by pimalel233** [stfwi/engineers-decor#90]
http://prntscr.com/r6jakf
Version: 1.0.19-B3

Options:
        # Disable decorative sign plates (caution, hazards, etc).
        B:"Without signs"=true
        # Disable registration of opt'ed out blocks. That is normally not a good idea. Your choice.
        B:"Without opt-out registration"=true

**Comment by stfwi** [comment]
Hi, yes, this one is needed as creative tab icon, so its excluded from this config. As it is also not craftable, we should be fine here. Does it make a special problem in a pack?

**Comment by pimalel233** [comment]
Hi, not really, just installed a mod and noticed the config did not remove everything, though it was not intended. I guess the biggest con of it is that it still uses a block ID so in some cases it might be that 'one ID' of difference (not counting mods expanding the limit). Personally it does not bother me much, though I tried to hide it with CraftTweaker and that also did not work.

**Comment by stfwi** [comment]
Ok, so I'll make an analog side note for 1.12 to check the item group settings for the sign, at the current stage I do not like to remove the block completely, as this would enforce admins and players to `/fml confirm` that a block is missing - but it should be possible to `null`ify the item group for the sign to get it out of the creative tab. I'll close this issue then - thanks again for the hint.

**Comment by pimalel233** [comment]
@stfwi If you are still insterested in doing something like that, it come to my mind you could do it in a non intrusive way. Thermal series mod uses a random item (I think) from the creative tab of its mod to show as an icon, which changes every n seconds. You could add an option that disables static icon (that also removes that item) and adds that kind of icon. Just a though.

**Comment by stfwi** [comment]
Hi, already fix it ;) The version is under review on Curse and should be available in the next hours.
1.12.2 is already in maintenance release state, so I try to keep changes as small as possible there.
