### ISSUE TITLE
Small Mineral Melting Furnace loosing Lava output

### ISSUE THREAD

**Issue by papaworld** [stfwi/engineers-decor#92]
MC: 1.15.2
FML: 31.1.30
Engineer's Decor: engineersdecor-1.15.2-1.0.20-b2

Using Mekanism Basic or Advanced Mechanical Pipe to remove Lava from Melting Furnace... I am only getting 100mb of the 1,000mb produced. I brought this issue up with the Mekanism team and they responded with the following:

The fluid voiding is a bug in Engineer's decor. (I am leaving this issue open for now to track/fix the fallback for before configs load that I found while looking for the issue.)
From what I can tell: https://github.com/stfwi/engineers-decor/blob/master/1.15/src/main/java/wile/engineersdecor/blocks/BlockDecorMineralSmelter.java#L494 they are ignoring the amount we request to drain and just are draining whatever is stored from their mineral smelter. The reason it worked before, is that their other drain method seems to be implemented properly, and we used to use that before I switched to the fluid stack specific one to have proper support for tile's that have more than one tank.

Is it possible to fix the issue? My Lava based smelting, FE power generators and bucket fillers no longer work.

Thank you

**Comment by stfwi** [comment]
Hi, aye, that is quite a glitch ;-). I'll schedule that for the weekend. Cheers -

**Comment by stfwi** [comment]
(Related issue https://github.com/mekanism/Mekanism/issues/6011).

**Comment by stfwi** [comment]
Like that ? ;-)

![2020-04-01_19 17 15](https://user-images.githubusercontent.com/28822525/78167066-1e216e80-744e-11ea-97a6-0dce9b6ec854.png)

**Comment by papaworld** [comment]
Hello, yes for the most part. Melter Lava output bottom to 1 piece of Mekanism Basic Mechanical Pipe (100mb pull rate). Used the configurator to set pipe to pull from Melter. Then to a tank. The tank receives only 100mb per Melt operation. (I did not use the wheel check valve.) With Mekanism Advanced Mech Pipe (400mb pull rate) the tank receives 400mb per operation.

BTW: really helpful mod, nice textures too.

**Comment by papaworld** [comment]
Found out if the Mechanical Pipe was not in pull mode... left at default connection, the amount transferred is correct. Thank you for your help. Enjoy!

**Comment by stfwi** [comment]
Cheers, the fix release is scheduled for this weekend (just need to double check with my local server again).

**Comment by stfwi** [comment]
Alright, the file is approved on curse. After my tests were ok, could you also make a quick check if the problem is resolved for your setup and close the issue if so? Cheers -
