### ISSUE TITLE
request: ingame manual

### ISSUE THREAD

**Issue by seppestuyck** [stfwi/engineers-decor#93]
Much like IE, but mostly to explain the UI of the devices without having to search for it online.

**Comment by stfwi** [comment]
Hi, for version 1.12.2 there is only the extended tooltip (holding shift-ctrl while hovering):
![2020-04-05_16 34 01](https://user-images.githubusercontent.com/28822525/78501388-e53e0e00-775b-11ea-8d2c-f7a324260290.png)

For 1.14/1.15 there is also a Patchouli based manual ("Engineer's Decor Reference Manual"):
![2020-04-05_16 35 04](https://user-images.githubusercontent.com/28822525/78501432-0141af80-775c-11ea-8f6d-672f2dbd4a25.png)
You need to install Vazkii's Patchouli mod for that, too.
Eventually the manual will be integrated in a section of the IE Engineer's Manual, but there is some stuff to do until then.

Does this answer your question?

**Comment by seppestuyck** [comment]
Ah, im currently playing in1.12, so i havent seen that manual yet.
Once i can recreate the modpack in 1.14+ ill make sure to check out the book.
Mainly had trouble with interpreting the ui of some of the blocks without going out of the game.

**Comment by stfwi** [comment]
Let me make a side note about the manual in 1.12, so that it's included when a maintenance version is needed and I have enough time to tackle that matter.

**Comment by stfwi** [comment]
Ok I have to admit adding the manual was quite easy as vazkii has kept a good consistency between the versions. It's in the uploaded maintenance release `1.12.2-1.0.20-b5` and available on Curse.
