### ISSUE TITLE
[Compatability/Enchancement] Double Slabs

### ISSUE THREAD

**Issue by pimalel233** [stfwi/engineers-decor#94]
https://github.com/CJMinecraft01/DoubleSlabs/issues/20#issuecomment-609057440
There is a minor incompatability that Double Slabs do not detect your slabs so they can not be improved by the other mod. Appratently it can be easly fixed by adding some extra code in the mod so that the slabs can be detected. Would be nice to see it happen. Thanks for the great mod!
MC version: 1.12.2

**Comment by stfwi** [comment]
Hi, cheers for pinging about that issue, normally I already moved on to 1.14+, but I'll collect and checkout the fix for a maintenance version then. Could take a bit of time though until tackling that.

**Comment by stfwi** [comment]
Took a quick peek and decided to redirect this with a PR, as my slabs contain additional data/variants and a good solution is probably to put that aspect into the Double Slabs mod.

**Comment by pimalel233** [comment]
Thank you kindly :)

**Comment by stfwi** [comment]
Perfect that, CJ has already merged it. I'll close the issue then.
