### ISSUE TITLE
Ticking Entity Crash after pushing Slab

### ISSUE THREAD

**Issue by NielsPilgaard** [stfwi/engineers-decor#95]
Hello!

I received a report from a player that his game crashed while pushing a slab with a Piston. Stacktrace indicates DoubleSlabs and Engineer's Decor, so I thought I'd report it both places.

https://gist.github.com/NillerMedDild/e5f403bc3bc957fcfa2db93eb6a3ca67

- DoubleSlabs-1.15-2.2.6
- engineersdecor-1.15.2-1.0.20-b6

**Comment by stfwi** [comment]
Hi, thanks for forwarding, I'll take a look at the weekend what's going wrong there. Cheers -

**Comment by stfwi** [comment]
Caught a first glimpse, I'll see that I can fix this on my side. Although my slabs are not derived from vanilla slabs (because of additional variation data), the state property checked for is kinda what other mods expect from something called "slab".

**Comment by CJMinecraft01** [comment]
I should have fixed this in the latest version! Sorry about that :)

**Comment by stfwi** [comment]
Thanks CJ, I'll close this issue then, too. Cheers -
